package com.polus.core.constants;

import java.math.BigDecimal;

public interface Constants {

    String DATABASE_BOOLEAN_TRUE_STRING_REPRESENTATION = "Y";
    String DATABASE_BOOLEAN_FALSE_STRING_REPRESENTATION = "N";

    String DESCRIPTION = "description";
    String HASH_ALGORITHM = "SHA";
    String CHARSET = "UTF-8";
    String EMAIL_NOTIFICATION_TEST_ADDRESS = "EMAIL_NOTIFICATION_TEST_ADDRESS";
    String ISACTIVE = "isActive";
	String SYSTEM_LOOKUP = "SystemLookup";
	String USER_LOOKUP = "UserLookup";
	String TABLE = "Table";
//
//    // Security constants
    String SECRET = "q3t6w9z$C&F)J@NcRfUjWnZr4u7x!A%D";
//    long EXPIRATION_TIME = 43_200_000; // 12 hour
    String TOKEN_PREFIX = "Bearer ";
    String HEADER_STRING = "Authorization";
//    String SIGN_UP_URL = "/fibi-comp/login";
//    String EXTERNAL_AUTHORIZATION = "EXTERNALAUTH";
    String TRUE = "Y";
//    Integer UNAUTHORIZED = 401;
    String LOGIN_PERSON_ID = "personId";
    String LOGIN_PERSON_UNIT = "unitNumber";
    String LOGIN_USER_FULL_NAME = "fullName";
    String IS_EXTERNAL_USER = "isExternalUser";
//
//    // Grant Call
//    Integer GRANT_CALL_STATUS_CODE_DRAFT = 1;
//    Integer GRANT_CALL_STATUS_CODE_OPEN = 2;
//    Integer GRANT_CALL_STATUS_CODE_CLOSED = 3;
//    Integer GRANT_CALL_STATUS_CODE_TENTATIVE = 4;
//    Integer GRANT_CALL_STATUS_CODE_ARCHIVED = 5;
//    Integer GRANT_CALL_STATUS_CODE_NOT_TO_PUBLISH = 6;
//
//    String GRANT_CALL_CATEGORY_A_TYPE_CODE = "7";
//    String GRANT_CALL_CATEGORY_B_TYPE_CODE = "8";
//    String GRANT_CALL_CATEGORY_C_TYPE_CODE = "9";
//
//    Integer GRANT_CALL_TYPE_INTERNAL = 1;
//    Integer GRANT_CALL_TYPE_EXTERNAL = 2;
//    Integer GRANT_CALL_TYPE_OTHERS = 3;
//    Integer GRANT_CALL_TYPE_INTERNAL_SIMPLE_EVALUATION = 5;
//    Integer GRANT_CALL_TYPE_EXTERNAL_SIMPLE_EVALUATION = 6;
//    Integer GRANT_CALL_TYPE_INTERNAL_NO_EVALUATION = 1;
//    Integer GRANT_CALL_TYPE_EXTERNAL_NO_EVALUATION = 2;
//    Integer GRANT_CALL_TYPE_ONLY_FOR_ADDING_GRANT_SCHEME = 10;
//    
//    Integer EXTERNAL_GRANT_ELIGIBILITY_TYPE_CODE = 3;
//
    // Proposal
    Integer PROPOSAL_STATUS_CODE_IN_PROGRESS = 1;
//    Integer PROPOSAL_STATUS_CODE_APPROVAL_INPROGRESS = 2;
//    Integer PROPOSAL_STATUS_CODE_AWARDED = 11;
//    Integer PROPOSAL_STATUS_CODE_RETURNED = 3;
//    Integer PROPOSAL_STATUS_CODE_WITHDRAW = 12;
//    Integer PROPOSAL_STATUS_CODE_INACTIVE = 35;
//    Integer PROPOSAL_STATUS_CODE_REVISION_REQUESTED = 9;
//    Integer ADMIN_CHECK_COMPLETED = 37;
//    Integer COMPLETED = 38;
//    Integer REVIEW_IN_PROGRESS = 8;
//    Integer PROPOSAL_STATUS_CODE_NOT_AWARDED = 41;
//    Integer PROPOSAL_STATUS_CODE_PENDING_REVISION_BY_PI = 20;
//    Integer PROPOSAL_STATUS_CODE_ORT_DIRECTOR_REVIEW_COMPLETED = 22;
//    Integer PROPOSAL_STATUS_CODE_PENDING_REVISION_BY_PI_ = 24;
//
//    // Route Log Status Code
    String WORKFLOW_STATUS_CODE_WAITING = "W";
//    String WORKFLOW_STATUS_CODE_APPROVED = "A";
//    String WORKFLOW_STATUS_CODE_REJECTED = "R";
//    String WORKFLOW_STATUS_CODE_BYPASSED = "B";
//    String WORKFLOW_STATUS_CODE_TO_BE_SUBMITTED = "T";
//    String WORKFLOW_STATUS_CODE_APPROVED_BY_OTHER = "AO";
//    String WORKFLOW_STATUS_CODE_REJECTED_BY_OTHER = "RO";
//    String WORKFLOW_STATUS_CODE_APPROVAL_BYPASSED = "AB";
//    String WORKFLOW_STATUS_CODE_REJECTED_BY_ADMIN = "RS";
//
//    // Workflow first stop number
//    Integer WORKFLOW_FIRST_STOP_NUMBER = 1;
//    Integer ADMIN_ROLE_TYPE_CODE = 2;
//    String FEDERAL_ROLE_TYPE_CODE = "0";
//    String NON_FEDERAL_ROLE_TYPE_CODE = "1";
//
//    // Protocol
//    String PROTOCOL_SATUS_CODE_ACTIVE_OPEN_TO_ENTROLLMENT = "200";
//
//    // Parameter Constants
//    String MODULE_NAMESPACE_PROPOSAL_DEVELOPMENT = "KC-PD";
//    String DOCUMENT_COMPONENT = "Document";
//    String FISCAL_YEAR_BASED_IP = "GENERATE_IP_BASED_ON_FY";
//    String NON_EMPLOYEE_CERTIFICATION = "NON_EMPLOYEE_CERTIFICATION";
//
//    // OST Status
//    Integer STATUS_AT_OSP_CODE = 1;
//    Integer STATUS_AT_DLC_NOT_SUBMITTED_CODE = 9;
//    Integer STATUS_PROCESSING_CODE = 7;
//    String STATUS_AT_DLC_NOT_SUBMITTED = "DLC-Not Submitted";
//    Integer ACTION_NEW_REQUEST = 8;
//    Integer ACTION_NEW_REPORTER = 10;
//    Integer STATUS_AT_POPS_CODE = 4;
//    Integer POPS_CATEGORY_CODE = 5;
//    Integer ACTION_SUBMIT = 15;
//    Integer OST_PRIORITY_NORMAL = 2;
//
//    // Budget Constants
//    String BUDGET_TAB_SIMPLE = "SIMPLE";
//    String DEFAULT_RATE_CLASS_CODE = "DEFAULT_RATE_CLASS_CODE";
//    String DEFAULT_RATE_TYPE_CODE = "DEFAULT_RATE_TYPE_CODE";
//    String DEFAULT_OH_RATE_CLASS_TYPE_CODE = "DEFAULT_OH_RATE_CLASS_TYPE_CODE";
//    String BUDGET_CATEGORY_CODE_TYPE_PERSONNEL = "P";
//    String COPY_TYPE_PROPOSAL = "ProposalCopy";
//    String COPY_APPROVED_BUDGET = "COPY_APPROVED_BUDGET";
//    String ENABLE_PROPOSAL_BUDGET_VERSIONS = "ENABLE_PROPOSAL_BUDGET_VERSIONS";
//    String IS_PERIODS_TOTAL_ENABLED = "IS_PERIODS_TOTAL_ENABLED";
//    String IS_BUDGET_SUMMARY_ENABLED = "IS_BUDGET_SUMMARY_ENABLED";
//    String IS_GENERATE_PERIODS_ENABLED = "IS_GENERATE_PERIODS_ENABLED";
//    String IMPORT_PD_BUDGET_TO_AWARD = "IMPORT_PD_BUDGET_TO_AWARD";
//    String FUND_TYPE_CODE = "O";
//
//    // Rate class code
//    String RATE_CLASS_CODE_INFLATION = "7";
//    String RATE_CLASS_CODE_EMPLOYEE_BENEFITS = "5";
//    String RATE_CLASS_CODE_MTDC = "1";
//    String RATE_CLASS_CODE_TYPE_EMPLOYEE_BENEFITS = "E";
//    String RATE_CLASS_CODE_TYPE_OVERHEAD = "O";
//    String RATE_CLASS_CODE_TYPE_INFLATION = "I";
//
//    String BUD_CAT_TOTAL_BY_BUD_CAT = "BUD_CAT_TOTAL_BY_BUD_CAT";
//    String ENABLE_SINGLE_PERIOD_BUDGET = "ENABLE_SINGLE_PERIOD_BUDGET";
//
//    String COST_TYPE_LINE_ITEM_COST = "LINE_ITEM_COST";
//    String COST_TYPE_COST_SHARE = "COST_SHARE";
//    String COST_TYPE_FUND_REQUESTED = "FUND_REQUESTED";

    public static final String STRING_TO_DATE_FORMATS = "STRING_TO_DATE_FORMATS";
    public static final String STRING_TO_TIME_FORMATS = "STRING_TO_TIME_FORMATS";
    public static final String STRING_TO_TIMESTAMP_FORMATS = "STRING_TO_TIMESTAMP_FORMATS";
    public static final String DATE_TO_STRING_FORMAT_FOR_USER_INTERFACE = "DATE_TO_STRING_FORMAT_FOR_USER_INTERFACE";
    public static final String TIME_TO_STRING_FORMAT_FOR_USER_INTERFACE = "TIME_TO_STRING_FORMAT_FOR_USER_INTERFACE";
    public static final String TIMESTAMP_TO_STRING_FORMAT_FOR_USER_INTERFACE = "TIMESTAMP_TO_STRING_FORMAT_FOR_USER_INTERFACE";
    public static final String DATE_TO_STRING_FORMAT_FOR_FILE_NAME = "DATE_TO_STRING_FORMAT_FOR_FILE_NAME";
    public static final String TIMESTAMP_TO_STRING_FORMAT_FOR_FILE_NAME = "TIMESTAMP_TO_STRING_FORMAT_FOR_FILE_NAME";

//    // System Generated CostElemets Details
//    public static final String BUDGET_RESEARCH_OH_ON = "BUDGET_RESEARCH_OH_ON";
//    public static final String BUDGET_RESEARCH_OH_OFF = "BUDGET_RESEARCH_OH_OFF";
//    public static final String BUDGET_OH_ON = "BUDGET_OH_ON";
//    public static final String BUDGET_OH_OFF = "BUDGET_OH_OFF";
//    public static final String BUDGET_FRINGE_ON = "BUDGET_FRINGE_ON";
//    public static final String BUDGET_FRINGE_OFF = "BUDGET_FRINGE_OFF";
//    public static final String ACTIVITY_TYPE_CODE_RESEARCH = "1";
//
//    // Enable Required Section
//    public static final String IS_REQUIRED_DECLARATION_SECTION = "IS_REQUIRED_DECLARATION_SECTION";
//
//    // Sponsor Type
//    String SPONSOR_TYPE_CODE_FEDERAL = "0";
//
//    // Move worker
//    String QUICKSTART = "quickstart";
//
//    // Attachment Status
//    String NARRATIVE_STATUS_CODE_INCOMPLETE = "I";
//    String NARRATIVE_STATUS_CODE_COMPLETE = "C";
//
//    // Proposal Pre Review Section
//    String PRE_REVIEW_STATUS_INPROGRESS = "1";
//    String PRE_REVIEW_STATUS_COMPLETE = "2";
//    String PRE_REVIEW_STATUS_REVISION = "3";
//
//    // Proposal Special Review Section
//    String SP_REV_APPROVAL_TYPE_LINK_TO_IRB = "5";
//    String SP_REV_APPROVAL_TYPE_LINK_TO_IACUC = "6";
//    String SP_REV_APPROVAL_TYPE_PENDING = "1";
//    String SP_REV_APPROVAL_TYPE_NOT_APPLICABLE = "7";
//
//    // Questionnaire completion flags
//    String QUESTIONNAIRE_COMPLETE_FLAG = "Y";
//    String QUESTIONNAIRE_INCOMPLETE_FLAG = "N";
//
//    // Change Password Status Message
//    String UPDATE_PASSWORD_SUCCESS_MESSAGE = "Password Updated Successfully";
//    String UPDATE_PASSWORD_ERROR_MESSAGE = "Error in update password";
//    String OLD_PASSWORD_ERROR_MESSAGE = "Invalid Old Password";
//
    // Unit Hierarchy
    String ROOT_UNIT = "000001";
//
//    // Document Status Code
//    Integer DOCUMENT_STATUS_CODE_DRAFT = 1;
//    Integer DOCUMENT_STATUS_CODE_ARCHIVED = 2;
//    Integer DOCUMENT_STATUS_CODE_DELETED = 3;
//
//    // PI role code
//    Integer PI_ROLE_CODE = 3;
//    Integer PI_ROLE_CODE_MULTI = 8;
//    Integer COI_ROLE_CODE = 1;
//
//    // Medusa
//    Integer negotiationModuleCode = 5;
//
//    // Negotiation
//    String negotiationStatusCodeCaseOne = "1";
//    String negotiationStatusCodeCaseTwo = "2";
//    String switchToAward = "1";
//    String switchToIP = "2";
//    String NEGOTIATION_MODE_INPROGRESS = "1";
//    String NEGOTIATION_MODE_SUSPENDED = "3";
//    String NEGOTIATION_MODE_WAITING_FOR_RESPONSE = "2";
//    String NEGOTIATION_STATUS_CODE_INPROGRESS = "1";
//    String NEGOTIATION_EDIT_MODE = "EDIT";
//    String NEGOTIATION_VIEW_MODE = "VIEW";
//    String NEGOTIATION_SHOW_SUBMIT_BUTTON = "1";
//
//    // Workflow
//    Integer workflowSuccess = 1;
//    Integer workflowFailed = 0;
//    Integer NEGOTIATION_STATUS_CODE_APPROVAL_INPROGRESS = 5;
//    Integer NEGOTIATION_STATUS_CODE_APPROVED = 6;
//    Integer NEGOTIATION_STATUS_CODE_RETURNED = 3;
//
    // acType
    String acTypeInsert = "I";
    String acTypeUpdate = "U";
    String acTypeDelete = "D";
    String acTypeReplace = "R";
//
//    // associationTypeCode
//    String ASSOCIATION_NONETYPE = "3";
//    String ASSOCIATION_IPTYPE = "2";
//    String ASSOCIATION_AWARDTYPE = "1";
//
//    // Award Module
//    String AWARD_FINAL_STATUS_ACTIVE = "ACTIVE";
//    String AWARD_FINAL_STATUS_ARCHIVE = "ARCHIVE";
//    String AWARD_FINAL_STATUS_PENDING = "PENDING";
//    String AWARD_FINAL_STATUS_CANCELLED = "CANCELLED";
//    String AWARD_STATUS_CODE_PENDING = "3";
//    String AWARD_STATUS_CODE_CLOSED = "5";
//    String AWARD_STATUS_CODE_AWARDED = "1";
//    String AWARD_STATUS_CODE_HOLD = "6";
//    String AWARD_STATUS_CODE_WITHDRAW = "11";
//    String AWARD_STATUS_CODE_RESCINDED = "12";
//    String AWARD_STATUS_CODE_CANCELLED = "13";
//    String AWARD_STATUS_CODE_EXPIRED = "14";
//
//    // Module Code
    Integer AWARD_MODULE_CODE = 1;
    Integer INSTITUTE_PROPOSAL_MODULE_CODE = 2;
    Integer DEV_PROPOSAL_MODULE_CODE = 3;
//    Integer NEGOTIATION_MODULE_CODE = 5;
//    Integer NDA_MODULE_CODE = 12;
//    Integer GRANTCALL_MODULE_CODE = 15;
//    Integer SERVICE_REQUEST_MODULE_CODE = 20;
    Integer PERSON_MODULE_CODE = 6;
//    Integer CLAIM_MODULE_CODE = 14;
//    Integer PROGRESS_REPORT_MODULE_CODE = 16;
    Integer EXTERNAL_USER_MODULE_CODE = 21;
//	  Integer MODULE_CODE_AGREEMENT = 13;
//    
//    // Sub Module Code
//    Integer DEV_PROPOSAL_SUBMODULE_CODE = 0;
//    Integer NEGOTIATION_SUBMODULE_CODE = 0;
//    Integer NDA_SUBMODULE_CODE = 0;
//    Integer AWARD_SUBMODULE_CODE = 0;
//    Integer AWARD_DMP_SUBMODULE_CODE = 3;
//    Integer PROPOSAL_EVALUATION_SUBMODULE_CODE = 4;
//    Integer GRANTCALL_SUBMODULE_CODE = 0;
//    Integer GRANTCALL_IOI_SUBMODULE_CODE = 1;
//    Integer PROPOSAL_PRE_REVIEW_SUBMODULE_CODE = 5;
//    Integer AWARD_PRE_REVIEW_SUBMODULE_CODE = 1;
//    Integer AWARD_TASK_SUBMODULE_CODE = 2;
//    Integer SERVICE_REQUEST_SUBMODULE_CODE = 0;
    Integer PERSON_SUBMODULE_CODE = 0;
//    Integer CLAIM_SUBMODULE_CODE = 0;
//    Integer MANPOWER_SUBMODULE_CODE = 4;
//    Integer PROGRESS_REPORT_SUBMODULE_CODE = 0;
    Integer EXTERNAL_USER_SUB_MODULE_CODE = 0;
//	Integer SUBMODULE_CODE = 0;
//	Integer DEV_PROPOSAL_PERSON_CERTIFICATION_SUBMODULE_CODE = 3;
//
//    // actionTypeCOde
//    String actionTypeCodeAttachment = "4";
//    String actionTypeDescriptionAttachment = "Add Attachment";
//    String actionTypeCodeNote = "5";
//    String actionTypeDescriptionNote = "Add Note";
//
    // database
    String dbOracle = "Y";
    String dbMySQL = "N";
//
//    // Medusa
//    Integer AWARD_MEDUSA = 1;
//    Integer INSTITUTEPROPOSAL_MEDUSA = 2;
//    Integer PROPOSALDEVELOPMENT_MEDUSA = 3;
//    Integer NEGOTIATION_MEDUSA = 5;
//    Integer GRANTCALL_MEDUSA = 15;
//
//    // Budget Status
//    String BUDGET_STATUS_INPROGRESS = "1";
//    String BUDGET_STATUS_SUBMITTED = "5";
//    String BUDGET_STATUS_COMPLETED = "3";
//
//    // Proposal Status for Evaluvation---- SMU
//    Integer PROPOSAL_STATUS_CODE_ORTT_REVIEW_IN_PROGRESS = 23;
//    Integer PROPOSAL_STATUS_CODE_ORTT_REVIEW_COMPLETED = 13;
//    Integer PROPOSAL_STATUS_CODE_GRANT_ADMIN_REVIEW_IN_PROGRESS = 14;
//    Integer PROPOSAL_STATUS_CODE_GRANT_ADMIN_REVIEW_COMPLETED = 15;
//    Integer PROPOSAL_STATUS_CODE_DEC_REVIEW_IN_PROGRESS = 16;
//    Integer PROPOSAL_STATUS_CODE_GRANT_ADMIN_FINAL_REVIEW_IN_PROGRESS = 17;
//    Integer PROPOSAL_STATUS_CODE_WAITING_FOR_ENDORSEMENT = 18;
//    Integer PROPOSAL_STATUS_CODE_ENDORSEMENT_COMPLETED = 19;
//    Integer PROPOSAL_STATUS_CODE_GRANT_MANAGER_RETURNED = 24;
//    Integer PROPOSAL_STATUS_CODE_GRANT_ADMIN_RETURNED = 20;
//    Integer PROPOSAL_STATUS_CODE_HOD_RETURNED = 22;
//    // Integer RETURNED_BY_ORTT = 24;
//    // Integer RETURNED_BY_SCHOOL_ADMIN = 20;
//    Integer PROPOSAL_STATUS_CODE_ORTT_DIRECTOR_REVIEW_IN_PROGRESS = 21;
//    Integer PROPOSAL_STATUS_CODE_HOD_REVIEW_IN_PROGRESS = 25;
//    Integer PROPOSAL_STATUS_CODE_HOD_REVIEW_COMPLETED = 26;
//    Integer PROPOSAL_STATUS_CODE_SUBMITTED_FOR_REVIEW = 27;
//    Integer PROPOSAL_STATUS_CODE_GRANT_MANAGER_FINAL_REVIEW_INPROGRESS = 28;
//    Integer PROPOSAL_STATUS_FUNDING_AGENCY_REVIEW = 31;
//    Integer PROPOSAL_STATUS_CODE_URC_COMPLETED = 39;
//
//    // Proposal Status for Evaluvation---- NTU
//    Integer PROPOSAL_STATUS_CODE_UNSUCCESSFUL = 29;
//    Integer PROPOSAL_STATUS_CODE_SHORTLISTED = 40;
//
//    // Proposal Status
//    Integer PROPOSAL_STATUS_CODE_NOT_SUBMITTED = 30;
//    // Proposal review type codes
//    Integer PROPOSAL_GRANT_MANAGER_ROLE_TYPE_CODE = 100;
//    Integer PROPOSAL_GRANT_ADMIN_ROLE_TYPE_CODE = 120;
//    Integer PROPOSAL_DEC_ROLE_TYPE_CODE = 200;
//
//    // Proposal Review Section
//    Integer PROPOSAL_REVIEW_STATUS_INPROGRESS = 1;
//    Integer PROPOSAL_REVIEW_STATUS_COMPLETE = 2;
//    Integer PROPOSAL_REVIEW_STATUS_REVISION = 3;
//    Integer PROPOSAL_REVIEW_STATUS_REVISION_BY_OTHER = 4;
//    Integer PROPOSAL_REVIEW_STATUS_UNSUCCESSFULL = 5;
//
//    // Notification_typeCode
//    Integer PROPOSAL_SUBMIT_NOTIFICATION_CODE = 10;
//    Integer APPLICATION_REVIEW_NOTIFICATION_CODE = 11;
//    Integer APPLICATION_REVIEW_REMINDER_NOTIFICATION_CODE = 12;
//    Integer COMPLETED_REVIEW_NOTIFICATION_CODE = 13;
//    Integer APPLICATION_REVISION_NOTIFICATION_CODE = 14;
//    Integer APPLICATION_REVISION_REMINDER_NOTIFICATION_CODE = 15;
//    Integer IRB_ASSESSMENT_NOTIFICATION_CODE = 16;
//    Integer IRB_ASSESSMENT_COMPLETION_NOTIFICATION_CODE = 17;
//    Integer APPLICATION_ENDORSEMENT_NOTIFICATION_CODE = 18;
//    Integer GRANT_CALL_OPENING_SCHEDULER_NOTIFICATION_CODE = 19;
//    Integer GRANT_CALL_OPENING_NOTIFICATION_CODE = 20;
//    Integer GRANT_CALL_CLOSING_NOTIFICATION_CODE = 21;
//    Integer NOTIFY_ACTION_NOTIFICATION_CODE = 506;
//    Integer PROPOSAL_APPROVE_NOTIFICATION_CODE = 301;
//    Integer NOTIFICATION_PROPOSAL_RESUBMISSION = 521;
//    Integer NOTIFICATION_FUND_PROPOSAL = 522;
//    Integer NOTIFICATION_CREATE_PROPOSAL_REVIEW = 523;
//    Integer NOTIFICATION_PROPOSAL_REJECTED = 302;
//    Integer AWARD_APPROVE_NOTIFICATION_CODE = 525;
//    Integer AWARD_REJECT_NOTIFICATION_CODE = 526;
//    Integer PROPOSAL_PERSON_ROLE_ADD_NOTIFICATION_CODE = 527;
//    Integer PROPOSAL_PERSON_ROLE_DELETE_NOTIFICATION_CODE = 528;
//    Integer NOTIFICATION_NEGOTIATION_SUBMIT = 501;
//    Integer GRANTCALL_IOI_NOTIFICATION_CODE = 529;
//    Integer GRANTCALL_UPDATE_NOTIFICATION_CODE = 530;
//    Integer GRANTCALL_PUBLISH_NOTIFICATION_CODE = 531;
//    Integer PROJECT_AWARDED_NOTIFICATION_CODE = 532;
//    Integer GRANT_ADMIN_AWARD_ASSIGN_NOTIFICATION_CODE = 538;
//	Integer FINANCE_AWARD_ASSIGN_NOTIFICATION_CODE = 539;
//    Integer LIVE_AWARD_NOTIFICATION_CODE = 540;
//    Integer SERVICE_REQUEST_OUTCOME_NOTIFICATION_CODE = 543;
//    Integer SERVICE_REQUEST_APPROVAL_NOTIFICATION_CODE = 544;
//    Integer ADMIN_CHECK_COMPLETE_NOTIFICATION_CODE = 547;
//    Integer SHORTLIST_PROPOSAL_NOTIFICATION_CODE = 548;
//    Integer PROPOSAL_AWARDED_NOTIFICATION_CODE = 303;
//    Integer FINAL_BYPASS_APPROVER_NOTIFICATION_CODE = 806;
//    Integer EVALUATION_PANEL_REVIEW_NOTIFICATION_CODE = 549;
//    Integer RA_SHORTLIST_PROPOSAL_NOTIFICATION_CODE = 550;
//    Integer RA_REJECT_PROPOSAL_NOTIFICATION_CODE = 551;
//    Integer RA_AWARDED_PROPOSAL_NOTIFICATION_CODE = 552;
//    Integer GRANT_CALL_MODIFICATION_NOTIFICATION_CODE = 553;
//    Integer ASSIGN_PROPOSAL_PRE_REVIEW_NOTIFICATION_CODE = 554;
//    Integer COMPLETE_PROPOSAL_PRE_REVIEW_NOTIFICATION_CODE = 555;
//    Integer RETURN_PROPOSAL_PRE_REVIEW_NOTIFICATION_CODE = 556;
//    Integer ASSIGN_AWARD_PRE_REVIEW_NOTIFICATION_CODE = 557;
//    Integer COMPLETE_AWARD_PRE_REVIEW_NOTIFICATION_CODE = 558;
//    Integer RETURN_AWARD_PRE_REVIEW_NOTIFICATION_CODE = 559;
//    Integer IRB_ASSIGN_AWARD_PRE_REVIEW_NOTIFICATION_CODE = 560;
//    Integer PI_ASSIGN_AWARD_PRE_REVIEW_NOTIFICATION_CODE = 561;
//    Integer MAIN_PANEL_EVALUATION_NOTIFICATION_CODE = 564;
//    Integer PI_ALL_PRE_REVIEWS_COMPLETE_NOTIFICATION_CODE = 566;
//    Integer SERVICE_REQUEST_REVISION_TO_PI_NOTIFICATION_CODE = 567;
//    Integer TASK_CREATED_NOTIFICATION_CODE = 568;
//    Integer TASK_REASSIGN_NOTIFICATION_CODE = 569;
//    Integer TASK_ASSIGNEE_REMOVED_NOTIFICATION_CODE = 570;
//    Integer TASK_SUBMITTED_NOTIFICATION_CODE = 574;
//    Integer TASK_APPROVE_NOTIFICATION_CODE = 571;
//    Integer TASK_RETURNED_NOTIFICATION_CODE = 573;
//    Integer AWARD_SUBMIT_NOTIFICATION_CODE = 575;
//    Integer TASK_ASSIGNEE_REMAINDER_NOTIFICATION_CODE = 576;
//    Integer ENABLE_POC_NOTIFICATION_ON_PUBLISH_GRANT_CALL = 572;
//    Integer TASK_REVIEW_COMPLETE_NOTIFICATION_CODE = 577;
//    Integer PERSON_FEED_API_NOTIFICATION_CODE = 578;
//    Integer REMINDER_NOTIFICATION_PROPOSAL = 579;
//    Integer REMINDER_NOTIFICATION_AWARD = 580;
//    Integer SERVICE_REQUEST_FOR_DMP_NOTIFICATION_CODE = 594;
//    Integer CREATE_VARIATION_REQUEST_NOTIFICATION = 595;
//    Integer TASK_FINANCE_ACCOUNT_CREATION_NOTIFICATION_CODE = 597;
//    Integer TASK_CONFIRM_PROJECT_DETAIS_COMPLETES_NOTIFICTION_CODE = 598;
//    Integer ADD_AWARD_ROLE_NOTIFICATION_CODE = 600;
//    Integer REMOVE_AWARD_ROLE_CODE = 601;
//    Integer TASK_BYPASS_NOTIFICATION_CODE = 602;
//    Integer TASK_DMP_NOTIFICATION_CODE = 603;
//    Integer SERVICE_REQUEST_WITHDRAW_NOTIFICATION_CODE = 604;
//    Integer TASK_REJECTED_NOTIFICATION_CODE = 605;
//    Integer SERVICE_REQUEST_CANCEL_NOTIFICATION_CODE = 606;
//    Integer AWARD_BYPASS_NOTIFICATION_CODE = 607;
//    Integer TASK_ASSIGNEE_SCHEDULER_REMAINDER_NOTIFICATION_CODE = 608;
//    Integer SERVICE_REQUEST_REVISION_NOTIFICATION_CODE = 626;
//    Integer AWARD_MAP_ROLE_MISSING_NOTIFICATION = 627;
//    Integer PROPOSAL_MAP_ROLE_MISSING_NOTIFICATION = 628;
//    Integer PROPOSAL_DEACTIVATE_NOTIFICATION_CODE = 636;
//    Integer PROPOSAL_BYPASS_NOTIFICATION_CODE = 638;
//    Integer PROPOSAL_FINAL_ENDORSEMENT_NOTIFICATION_CODE = 640;
//    Integer MANPOWER_VARIATION_FINAL_APPROVAL = 723;
//
//    Integer NOTIFICATION_PROPOSAL_ATTACHMENT_NOTIFICATION = 304;
//    Integer NOTIFICATION_PROPOSAL_ATTACHMENT_APPROVER = 305;
//    Integer NOTIFICATION_WITHDRAWAL_PROPOSAL = 306;
//    Integer NOTIFICATION_IP_GENERATED = 307;
//    Integer NOTIFICATION_NEGOTIATION_APPROVED = 502;
//    Integer NOTIFICATION_NEGOTIATION_REJECTED = 503;
//    Integer NOTIFICATION_NEGOTIATION_FINAL_APPROVED = 504;
//    Integer CLAIM_SUBMITTED_NOTIFICATION_CODE = 641;
//    Integer CLAIM_REVISION_NOTIFICATION_CODE = 642;
//    Integer CLAIM_APPROVAL_NOTIFICATION_CODE = 643;
//    Integer CLAIM_BYPASS_NOTIFICATION_CODE = 644;
//    Integer CLAIM_COMPLETE_NOTIFICATION_CODE = 645;
//    Integer CLAIM_MAP_ROLE_MISSING_NOTIFICATION = 646;
//    Integer MANPOWER_COMMITTED_AMOUNT_EXCEEDS_NOTIFICATION = 648;
//    Integer EVALUATION_PERSON_REMOVE_NOTIFICATION_CODE = 649;
//    Integer ICS_INTEGRATION_NOTIFICATION_CODE = 668;
//    Integer MANPOWER_HRBP_DETAIL_NOTIFICATION_CODE = 647;
//    Integer SAP_FEED_FAILED_NOTIFICATION_CODE = 670;
//    Integer SAP_FEED_REINTERFACE_NOTIFICATION_CODE = 671;
//    Integer MANPOWER_POSITION_FREEZE_ERROR_NOTIFICATION_CODE = 672;
//    Integer MANPOWER_COST_RECONCILATION_NOTIFICATION = 673;
//    Integer MANPOWER_COST_ALLOCATION_LESS_THAN_HUNDRED_NOTIFICATION_CODE = 674;
//    Integer MANPOWER_CLOSE_POSITION_NOTIFICATION = 675;
//    Integer MANPOWER_WORKDAY_TERMINATION_OR_LONG_LEAVE = 676;
//    Integer PROGRESS_REPORT_SUBMITTED_NOTIFICATION_CODE = 655;
//    Integer PROGRESS_REPORT_COMPLETE_NOTIFICATION_CODE = 660;
//    Integer PROGRESS_REPORT_APPROVAL_NOTIFICATION_CODE = 658;
//    Integer PROGRESS_REPORT_REVISION_NOTIFICATION_CODE = 657;
//    Integer PROGRESS_REPORT_BYPASS_NOTIFICATION_CODE = 659;
//    Integer PROGRESS_REPORT_MAP_ROLE_MISSING_NOTIFICATION = 661;
//    Integer MANPOWER_HRBP_UPGRADE_DETAIL_NOTIFICATION_CODE = 685;
//    Integer MANPOWER_INACTIVE_PERSON_NOTIFICATION_CODE = 687;
//    Integer MANPOWER_INTEGRATION_CUTOFF_CITS_NOTIFICATION = 688;
//    Integer MANPOWER_LOG_MAIL_NOTIFICATOIN_CODE = 690;
//    Integer MANPOWER_JOB_PROFILE_MAIL_NOTIFICATOIN_CODE = 693;
//    Integer MANPOWER_SCHEDULER_MAIL_NOTIFICATION = 694;
    Integer DELEGATION_REQUEST_NOTIFICATION_CODE = 699;
    Integer DELEGATION_ACCEPT_NOTIFICATION_CODE = 700;
    Integer DELEGATION_DENIED_NOTIFICATION_CODE = 701;
    Integer DELEGATION_REMOVED_NOTIFICATION_CODE = 702;
//    Integer MOVE_WORKERS_NOTIFICATION_CODE = 703;
//    Integer EXCLUDED_CLOSE_POSITION_NOTIFICATION_CODE = 705;
//    Integer EXCLUDED_FREEZE_POSITION_NOTIFICATION_CODE = 706;
//    Integer MANPOWER_HIRING_ON_EXISTING_POSITION_NOTIFICATION_CODE = 707;
//    Integer MANPOWER_LESS_COST_ALLOCATION_NOTIFICATION_CODE = 708;
//    Integer MANPOWER_CHANGE_IN_PI_SUPERIOR_NOTIFICATION_CODE = 709;
//    Integer PROPOSAL_UNSUCCESSFUL_NOTIFICATION_CODE = 710;
    Integer EXTERNAL_USER_APPROVED_NOTIFICATION_CODE = 724;
    Integer EXTERNAL_USER_REJECTED_NOTIFICATION_CODE = 725;    
//    Integer MANPOWER_COST_ALLOC_LESS_THAN_HUNDRED_SCHEDULER_NOTIFICATION_CODE = 726;
    Integer EXTERNAL_SGAF_USER_APPROVED_NOTIFICATION_CODE = 727;
//    Integer SAP_CLAIM_FEED_REVISION_NOTIFICATION_CODE = 730;
    Integer EXTERNAL_USER_PASSWORD_NOTIFICATION_CODE = 731;
    Integer EXTERNAL_USER_GRANT_MANAGER_NOTIFICATION_CODE = 732;
//    Integer SAP_CLAIM_FEED_RE_INTERFACE_NOTIFICATION_CODE = 734;
//    Integer SAP_CLAIM_FEED_INTERFACE_GEN_NOTIFICATION_CODE = 1401;
//    Integer SAP_CLAIM_FEED_INTERFACE_RES_NOTIFICATION_CODE = 1402;
//    Integer SAP_CLAIM_FEED_INTERFACE_GEN_ERR_NOTIFICATION_CODE = 1403;
//    Integer SAP_CLAIM_FEED_INTERFACE_RES_ERR_NOTIFICATION_CODE = 1404;
//    Integer LIVE_AWARD_NOTIFICATION_FOR_CLAIM_PREPARER_CODE = 735;
//    Integer SAP_CLAIM_FEED_E_INVOICE_NOTIFICATION_CODE = 738;
    Integer NOTIFICATION_PROPOSAL_PERSONS = 741;
//    Integer NOTIFICATION_PROPOSAL_PERSON_COMPLETE = 742;
//    Integer NOTIFICATION_PROPOSAL_PERSON_ALL_COMPLETE = 743;
//    Integer AGREEMENT_APPROVAL_NOTIFICATION_CODE = 751;
//    Integer CREATE_SUPPORT_REQUEST_NOTIFICATION_CODE = 1415;
//    Integer REPLY_SUPPORT_REQUEST_NOTIFICATION_CODE = 1416;
//    Integer PROPOSAL_STATUS_CODE_GRANT_ADMIN_REVIEW_IN_PROGRESS_NOTIFICATION_CODE = 1420;
//    Integer MANPOWER_NEW_HIRE_DETAIL_NOTIFICATION_CODE = 1417;
//    Integer PERSON_REACTIVE_MAIL = 804;
//
    // Module codes
    Integer MODULE_CODE_AWARD = 1;
//    Integer MODULE_CODE_INSTITUTE_PROPOSAL = 2;
    Integer MODULE_CODE_DEVELOPMENT_PROPOSAL = 3;
//    Integer MODULE_CODE_SUBCONTRACTS = 4;
//    Integer MODULE_CODE_NEGOTIATIONS = 5;
//    Integer MODULE_CODE_PERSON = 6;
//    Integer MODULE_CODE_IRB = 7;
//    Integer MODULE_CODE_COI_DISCLOSURE = 8;
//    Integer MODULE_CODE_IACUC_PROTOCOL = 9;
//    Integer MODULE_CODE_COMMITTEE = 11;
//    Integer MODULE_CODE_NDA = 12;
//    Integer MODULE_CODE_GRANT_CALL = 15;
//    Integer MODULE_CODE_SERVICE_REQUEST = 20;
//
//    String SMU_GRANT_ADMINISTRATOR = "GRANT_ADMIN";
//    String SMU_GRANT_MANAGER = "GRANT_MANAGER";
//    Integer UNIT_ADMIN = 3;
//    Integer SUPER_USER = 1;
//    String SMU_DEC = "DEC_REVIEWER";
//    String SMU_PROVOST = "VICE_PROVOST";
//    String SMU_URC = "URC";
//    String SMU_PI = "PI";
//    String SMU_IRB_SECRETARIAT = "IRB_ADMINISTRATOR";
//    String SMU_HOD = "HOD";
//    String SMU_ORTT_DIRECTOR = "ORTT_DIRECTOR";
//
//    // Application Enviornment
//    String EVALUATION = "EVALUATION";
//    String MAP_ROUTING = "MAP_ROUTING";
//    String EVALUATION_MAP_ROUTING = "EVALUATION_MAP_ROUTING";
//    String WORKFLOW_TYPE = "WORKFLOW_TYPE";
    String SPONSOR_FORMAT = "SPONSOR_CODE - SPONSOR_NAME (SPONSOR_ACRONYM)";
    String UNIT_FORMAT = "UNIT_NUMBER - UNIT_NAME";
//
//    // Award Report Tracking
//    String AWARD_EXECUTION_DATE = "1";
//    String AWARD_EFFECTIVE_DATE = "2";
//    String AWARD_EXPIRATION_DATE_OF_OBLIGATION = "3";
//    String FINAL_EXPIRATION_DATE = "4";
//    String AWARD_EFFECTIVE_DATE_OF_OBLIGATION = "5";
//    String FINANCIAL_YEAR = "7";
//    String CALENDAR_YEAR = "8";
//    String PERIOD_IN_YEARS_WHEN_FREQUENCY_BASE_IS_FINAL_EXPIRATION_DATE = "1";
//    String ZERO_HOURS = "00:00";
//    String PENDING_REPORT_STATUS_CODE = "1";
//
//    // Service Request role type codes
//    String ROLE_TYPE_DLC = "1";
//    String ROLE_TYPE_POPS_TEAM = "2";
//    String ROLE_TYPE_ACA = "3";
//
//    // Service Request Action Type Codes
//    Integer NEW_REQUEST_ACTION_CODE = 1;
//    Integer SUBMIT_ACTION_CODE = 2;
//    Integer ASSIGN_ACTION_CODE = 3;
//    Integer ASSIGN_TO_ME_ACTION_CODE = 4;
//    Integer APPROVED_ACTION_CODE = 5;
//    Integer RETURN_IN_ROUTE_LOG_ACTION_CODE = 6;
//    Integer REOPEN_ACTION_CODE = 7;
//    Integer EDIT_REQUEST_ACTION_CODE = 8;
//    Integer CANCEL_ACTION_CODE = 9;
//    Integer ADD_COMMENT_ACTION_CODE = 10;
//    Integer ADD_ATTACHMENT_ACTION_CODE = 11;
//    Integer ADD_WATCHER_ACTION_CODE = 12;
//    Integer REMOVE_WATCHER_ACTION_CODE = 13;
//    Integer RESUBMIT_ACTION_CODE = 14;
//    Integer REPORTER_CHANGE_ACTION_CODE = 15;
//    Integer CLOSE_REQUEST_ACTION_CODE = 16;
//    Integer RESOLVED_ACTION_CODE = 17;
//    Integer WITHDRAW_ACTION_CODE = 18;
//    Integer RETURN_BY_REPORTER_LOG_ACTION_CODE = 19;
//
//    // Service request type codes
//    String PROJECT_EXTENSION_SERVICE_REQUEST_TYPE_CODE = "1";
//    String BUDGET_VARIATION_SERVICE_REQUEST_TYPE_CODE = "4";
//    String BUDGET_VARIATION_INTRA_SERVICE_REQUEST_TYPE_CODE = "9";
//    String BUDGET_VARIATION_NEW_FUNDABLE_SERVICE_REQUEST_TYPE_CODE = "10";
//    String BUDGET_VARIATION_NON_STANDARD_SERVICE_REQUEST_TYPE_CODE = "12";
//    String PROJECT_SCOPE_SERVICE_REQUEST_TYPE_CODE = "3";
//    String TEAM_MEMBERS_CHANGE_SERVICE_REQUEST_TYPE_CODE = "2";
//    String OTHER_SERVICE_REQUEST_TYPE_CODE = "5";
//    String ALL_SERVICE_REQUEST_TYPE_CODE = "6";
//    String PROJECT_CLOSURE_TYPE_CODE = "7";
//    String AWARD_OUTCOME_TYPE_CODE = "8";
//
//    public static final String PROPOSAL_BUDGET_PERIOD_GENERATION_BASED_ON_CALENDAR_YEAR = "PROPOSAL_BUDGET_PERIOD_GENERATION_BASED_ON_CALENDAR_YEAR";
//    public static final String AWARD_BUDGET_GENERATION_BASED_ON_CALENDAR_YEAR = "AWARD_BUDGET_PERIOD_GENERATION_BASED_ON_CALENDAR_YEAR";
//
//    // External API Integration
//    public static final String IS_OTHER_FUNDING_SUPPORT_REQUIRED = "IS_OTHER_FUNDING_SUPPORT_REQUIRED";
//
//    // RCBF
//    public static final String RCBF_PROPOSAL = "500";
//    String IS_RCBF = "IS_RCBF_EVALUATION";
//    String RCBF_TYPE_CODE = "RCBF_TYPE_CODE";
//    String RCBF_STATUS_CODE = "RCBF_STATUS_CODE";
//    String RCBF_FUNDING_SCHEME_STATUS_CODE = "100";
//    String RCBF_FUNDING_SCHEME_STATUS = "RCBF_FUNDING_SCHEME_STATUS_CODE";
//
//    String DEFAULT_BUDGET_IS_AUTO_CALCULATION = "DEFAULT_BUDGET_IS_AUTO_CALCULATION";
//    String DEFAULT_AWARD_BUDGET_IS_AUTO_CALCULATION = "DEFAULT_AWARD_BUDGET_IS_AUTO_CALCULATION";
//
//    // Budget Tab flags
//    String IS_DETAILED_BUDGET_ENABLED = "IS_DETAILED_BUDGET_ENABLED";
//    String IS_MODULAR_BUDGET_ENABLED = "IS_MODULAR_BUDGET_ENABLED";
//    String IS_SIMPLE_BUDGET_ENABLED = "IS_SIMPLE_BUDGET_ENABLED";
//    String IS_ENABLE_AUTO_CALCULATE = "ENABLE_AUTO_CALCULATE";
//    String IS_ENABLE_AWARD_BUDGET_AUTO_CALCULATE = "ENABLE_AWARD_BUDGET_AUTO_CALCULATE";
//    String IS_ENABLE_SYS_GENERATED_COST_ELEMENT = "ENABLE_SYSTEM_GENERATED_COST_ELEMENT";
//    String ENABLE_DEFAULT_APPLICABLE_RATE_FOR_INTERNAL_TYPE = "ENABLE_DEFAULT_APPLICABLE_RATE_FOR_INTERNAL_TYPE";
//    String PROPOSAL_BUDGET_ENABLE_SINGLE_PERIOD = "PROPOSAL_BUDGET_ENABLE_SINGLE_PERIOD";
//    String COST_ELEMENT_FROM_TEMPLATE = "COST_ELEMENT_FROM_TEMPLATE";
//    String IS_CALCULATION_WITH_PREDEFINED_SALARY = "IS_CALCULATION_WITH_PREDEFINED_SALARY";
//    String IS_SHOW_IN_KIND = "IS_SHOW_IN_KIND";
//    String IS_SHOW_COST_SHARE_AND_UNDERRECOVERY = "IS_SHOW_COST_SHARE_AND_UNDERRECOVERY";
//    String IS_SHOW_MODIFIED_DIRECT_COST = "IS_SHOW_MODIFIED_DIRECT_COST";
//    String ENABLE_PERSONNEL_LINE_ITEM_DELETE_ON_LAST_PERSON_DELETE = "REMOVE_PERSONNEL_LINE_ITEM_ON_LAST_PERSON_DELETE";
//    String ENABLE_AB_PERSON_APPL_SAL_CALC = "ENABLE_AB_PERSON_APPL_SAL_CALC";
//    String SHOW_BUDGET_OH_RATE_PERCENTAGE = "SHOW_BUDGET_OH_RATE_PERCENTAGE ";
//    // Application-ID Parameter
//    String IS_APPLICATION_ID_REQUIRED = "IS_APPLICATION_ID_REQUIRED";
//
//    // Eligibility criteria
//    String ENABLE_ELIGIBILITY_CRITERIA = "ENABLE_ELIGIBILITY_CRITERIA";
//
    // ROLE_RIGHT MAINTENANCE
    String ADD_ROLE_RIGHT = "ARR";
    String DELETE_ROLE_RIGHT = "DRR";
//
//    // MessageType code
//    String MESSAGE_TYPE_EVALUATION = "108";
//    String MESSAGE_TYPE_PROPOSAL_REJECT = "105";
//    String MESSAGE_TYPE_PRE_REVIEW = "111";
//    String MESSAGE_TYPE_START_EVALUATION = "112";
//    String MESSAGE_TYPE_AWARD_REJECT = "106";
//    String MESSAGE_TYPE_AWARD_PRE_REVIEW = "113";
//    String MESSAGE_TYPE_NEGOTIATION_REJECT = "107";
//    String MESSAGE_TYPE_TASK_APPROVAL = "114";
//    String MESSAGE_TYPE_TASK_REJECT = "115";
//    String MESSAGE_TYPE_ASSIGN_TASK = "116";
//    String MESSAGE_TYPE_VARIATION_RETURN = "121";
//    String MESSAGE_TYPE_CLAIM_APPROVAL = "123";
//    String MESSAGE_TYPE_CLAIM_REJECT = "124";
//    String MESSAGE_TYPE_MAIN_PANEL_REVIEW = "128";
//    String MESSAGE_TYPE_PROGRESS_REPORT_APPROVAL = "126";
//    String MESSAGE_TYPE_PROGRESS_REPORT_REJECT = "127";
    String MESSAGE_TYPE_DELEGATION_REQUESTED = "129";
//    String MESSAGE_TYPE_SR_REJECT = "136";
//    String MESSAGE_TYPE_SR_ASSIGN = "137";
//
//    // Subject Type code
//    String SUBJECT_TYPE_CODE = "E";
//
//    Integer SERVICE_REQUEST_STATUS_CODE_DRAFT = 1;
//    Integer SERVICE_REQUEST_STATUS_CODE_APPROVAL_IN_PROGRESS = 2;
//    Integer SERVICE_REQUEST_STATUS_CODE_APPROVED = 4;
//    Integer SERVICE_REQUEST_STATUS_CODE_RETURNED = 3;
//    Integer SERVICE_REQUEST_STATUS_CODE_RESOLVED = 5;
//    Integer SERVICE_REQUEST_STATUS_CODE_REOPEN = 6;
//    Integer SERVICE_REQUEST_STATUS_CODE_REJECT = 7;
//    Integer SERVICE_REQUEST_STATUS_CODE_CLOSED = 8;
//    Integer SERVICE_REQUEST_STATUS_CODE_INPROGRESS = 9;
//    Integer SERVICE_REQUEST_STATUS_CODE_WITHDRAW = 10;
//    Integer SERVICE_REQUEST_STATUS_CODE_CANCEL = 11;
//
//    Integer SERVICE_REQUEST_COMMENT_NOTIFICATION_CODE = 507;
//    Integer RETURN_SERVICE_REQUEST_NOTIFICATION_CODE = 508;
//    Integer RESOLVE_SERVICE_REQUEST_NOTIFICATION_CODE = 509;
//    Integer ADD_SERVICE_REQUEST_ATTACHMENT_NOTIFICATION_CODE = 510;
//    Integer ASSIGN_TO_USER_SERVICE_REQUEST_NOTIFICATION_CODE = 511;
//    Integer REJECT_SERVICE_REQUEST_NOTIFICATION_CODE = 512;
//    Integer COMPLETE_SERVICE_REQUEST_NOTIFICATION_CODE = 513;
//    Integer EDIT_SERVICE_REQUEST_NOTIFICATION_CODE = 514;
//    Integer ADD_WATCHER_SERVICE_REQUEST_NOTIFICATION_CODE = 515;
//    Integer SERVICE_REQUEST_STATUS_UPDATE_REPORTER_NOTIFICATION_CODE = 516;
//    Integer SERVICE_REQUEST_STATUS_UPDATE_WATCHER_NOTIFICATION_CODE = 517;
//    Integer ASSIGN_SERVICE_REQUEST_NOTIFICATION_CODE_FOR_GROUP = 518;
//    Integer ASSIGN_SERVICE_REQUEST_NOTIFICATION_CODE_FOR_REPORTER = 519;
//    Integer SUBMIT_SERVICE_REQUEST_NOTIFICATION_CODE = 520;
//
//    // Letter Template type codes
//    String PROPOSAL_LETTER_TEMPLATE_TYPE_CODE = "106";
//    String BUDGET_LETTER_TEMPLATE_TYPE_CODE = "107";
//    String AWARD_LETTER_TEMPLATE_TYPE_CODE = "108";
//    String CP_LETTER_TEMPLATE_TYPE_CODE = "119";
//    String SERVICE_REQUEST_QUESTIONNAIRE_LETTER_TEMPLATE_TYPE_CODE ="121";
    String PLACEHOLDER_GRANT_CALL = "PLACEHOLDER_GRANT_CALL";
    String PLACEHOLDER_DEV_PROPOSAL = "PLACEHOLDER_DEV_PROPOSAL";
    String PLACEHOLDER_NEGOTIATION = "PLACEHOLDER_NEGOTIATION";
    String PLACEHOLDER_AWARD = "PLACEHOLDER_AWARD";
    String PLACEHOLDER_INSTITUTE_PROPOSAL = "PLACEHOLDER_INSTITUTE_PROPOSAL";
    String PLACEHOLDER_SERVICE_REQUEST = "PLACEHOLDER_SERVICE_REQUEST";
//    String AWARD_NOTICE_LETTER_TEMPLATE_TYPE_CODE = "109";
//    String AWARD_BUDGET_LETTER_TEMPLATE_TYPE_CODE = "110";
//    String AWARD_BUDGET_TIER_TEMPLATE_TYPE_CODE = "111";
//    String AWARD_BUDGET_NOTICE_TEMPLATE_TYPE_CODE = "112";
//    String BUDGET_SUMMARY_LETTER_TEMPLATE_TYPE_CODE = "113";
//    String AWARD_BUDGET_VARIATION_REQUEST_LETTER_TEMPLATE_TYPE_CODE = "114";
//    String AWARD_QUESTIONNAIRE_LETTER_TEMPLATE_TYPE_CODE = "115";
//    String PROPOSAL_QUESTIONNAIRE_LETTER_TEMPLATE_TYPE_CODE = "116";
//    String AWARD_DMP_QUESTIONNAIRE_LETTER_TEMPLATE_TYPE_CODE = "117";
//    String BUDGET_VARIATION_REQUEST_LETTER_TEMPLATE_TYPE_CODE = "118";
    String PLACEHOLDER_CLAIM = "PLACEHOLDER_CLAIM";
    String PLACEHOLDER_EXTERNAL_USER = "PLACEHOLDER_EXTERNAL_USER";
    String PLACEHOLDER_PROGRESS_REPORT = "PLACEHOLDER_PROGRESS_REPORT";
    String PLACEHOLDER_EXTERNAL_REVIEWER = "PLACEHOLDER_EXTERNAL_REVIEWER";
//
//    // Role
//    Integer PROPOSAL_AGGREGATOR_ROLE_ID = 5;
//    Integer PROPOSAL_BUDGET_CREATOR_ROLE_ID = 6;
//    Integer VIEW_PROPOSAL_ROLE_ID = 7;
//    Integer CREATE_VARIATION_REQUEST = 14;
//    Integer INITIATE_PROJECT_CLOSSURE = 45;
//    Integer MODIFY_AWARD_OUTCOME = 47;
//    Integer WITHDRAW_AWARD = 48;
//    Integer VIEW_AWARD_ROLE_ID = 13;
//    Integer MODIFY_AWARD = 12;
//
    // Notification Recepient Types
    String NOTIFICATION_RECIPIENT_TYPE_TO = "TO";
    String NOTIFICATION_RECIPIENT_TYPE_CC = "CC";
    String NOTIFICATION_RECIPIENT_TYPE_BCC = "BCC";
//
//    // Award WorkFolw Status
    String AWARD_WORKFLOW_STATUS_DRAFT = "1";
//    String AWARD_WORKFLOW_STATUS_APPROVAL_INPROGRESS = "2";
//    String AWARD_WORKFLOW_STATUS_ACTIVE = "3";
    String AWARD_WORKFLOW_STATUS_REVISION_REQUESTED = "4";
//    String AWARD_WORKFLOW_STATUS_HOLD = "5";
//    String AWARD_WORKFLOW_STATUS_HOLD_FOR_SAP = "6";
//    String AWARD_WORKFLOW_STATUS_WITHDRAWN = "7";
//
//    // Budget Types
//    String BUDGET_TYPE_NEW = "1";
//    String BUDGET_TYPE_REBUDGET = "2";
//
//    String AWARD_BUDGET_SINGLE_PERIOD_ENABLED = "AWARD_BUDGET_SINGLE_PERIOD_ENABLED";
//    String DEFAULT_AB_TBN_PERSON_ID = "DEFAULT_AB_TBN_PERSON_ID";
//    String TBN_PERSON_TYPE = "T";
//    String NON_EMPLOYEE_TYPE = "N";
//    String EMPLOYEE_PERSON_TYPE = "E";
//    String PROPOSAL_PERSON_TYPE = "P";
//
//    // Award Document type code
//    String MASTER_AWARD = "0";
//    String AWARD_SETUP = "1";
//    String AWARD_MODIFICATION = "2";
//    String AWARD_VARIATION = "3";
//
//    // Budget Category Type
//    String BUDGET_CATEGORY_TYPE_CODE_BUDGET_SUMMARY_TOTAL = "500";
//    String BUDGET_CATEGORY_TYPE_CODE_SYS_GENERATED_COST = "600";
//
//    // Institute Proposal
//    Integer IP_STATUS_PENDING = 1; 
//    Integer IP_STATUS_FUNDED = 2;
//
//    // Rate class code
//    String EMPLOYEE_BENEFIT_RATE_CLASS_CODE = "5";
//    String MTDC_RATE_CLASS_CODE = "1";
//
//    // Budget category code
//    String BUDGET_CATEGORY_CODE_FANDA = "10";
//    // String BUDGET_CATEGORY_CODE_EQUIPMENT = "11";
//    // String BUDGET_CATEGORY_CODE_SUBCONTRACT = "22";
//    String BUDGET_CATEGORY_TYPE_CODE_EQUIPMENT = "E";
//    String BUDGET_CATEGORY_TYPE_CODE_SUBCONTRACT = "S";
//    String BUDGET_CATEGORY_CODE_EOM = "EOM";
//    String BUDGET_CATEGORY_CODE_RSS = "RSS";
//
//    // Award Budget Type Codes
//    String AWARD_BUDGET_TYPE_CODE_NEW = "1";
//    String AWARD_BUDGET_TYPE_CODE_REBUDGET = "2";
//
//    // Award Budget Status codes
//    String AWARD_BUDGET_STATUS_CODE_INPROGRESS = "1";
//    String AWARD_BUDGET_STATUS_CODE_ACTIVE = "10";
//    String AWARD_BUDGET_STATUS_CODE_ERROR_IN_POSTING = "11";
//    String AWARD_BUDGET_STATUS_CODE_SUBMITTED = "5";
//    String AWARD_BUDGET_STATUS_CODE_REJECTED = "8";
//    String AWARD_BUDGET_STATUS_CODE_POSTED = "9";
//
//    // Award Attachment type
//    String AWARD_ATTACHMENT_TYPE_LETTER_OF_TEMPLATE = "3";
//    String AWARD_ATTACHMENT_LETTER_OF_ACCEPTANCE = "6";
//
//    // For checking user has Research Office Administrator role in Grant Call IOI
//    Integer RESEARCH_OFFICE_ADMINISTRATOR_ROLE_ID = 28;
//    Integer DRSO_ROLE_ID = 617;
//    Integer FINANCE_OFFICER = 652;
//
//    // Grant Call IOI Status
//    Integer GRANT_CALL_IOI_STATUS_CODE_DRAFT = 1;
//    Integer GRANT_CALL_IOI_STATUS_CODE_SUBMITTED = 2;
//    String GRANT_ADMIN_TYPE_CODE = "10";
//
//    String AWARD_ASSOCIATION_TYPE = "1";
//    String PROPOSAL_ASSOCIATION_TYPE = "2";
//    String EXTERNAL_ASSOCIATION_TYPE = "3";
//
//    String RIGHT_VIEW_GRANT_CALL_APPLICATIONS = "VIEW_GRANT_CALL_APPLICATIONS";
//    Integer GRANT_ADMINISTRATOR_ROLE_ID = 120;
//    Integer GRANT_MANAGER_ROLE_ID = 100;
//
//    // Person Role Type codes
//    Integer GRANT_MANAGER_ROLE_TYPE_CODE = 13;
//    Integer GRANT_ADMINISTRATOR_ROLE_TYPE_CODE = 14;
//    Integer ORTT_DIRECTOR_ROLE_TYPE_CODE = 12;
//    Integer IRB_SECRETARIAT_ROLE_TYPE_CODE = 18;
//    Integer FINANCE_ROLE_TYPE_CODE = 11;
//    Integer DEAN_ROLE_TYPE_CODE = 3;
//    Integer HOD_ROLE_TYPE_CODE = 2;
//
//    // Simple Evaluation Panel Map Id
//    Integer SIMPLE_EVALUATION_PANEL_MAP_ID = 134;
//    String IS_ENABLED_ADMIN_CHK = "IS_ENABLED_ADMIN_CHK";
//
//    // NTU Role Type Code
//    Integer PROPOSAL_HOD_ROLE_TYPE_CODE = 400;
//    // SMU Role Type Code
//    //Integer PROPOSAL_HOD_ROLE_TYPE_CODE = 656;
//    Integer PROPOSAL_RCBF_ROLE_TYPE_CODE = 655;
//    Integer RESEARCH_ADMINISTRATOR_ROLE_TYPE_CODE = 619;
//    Integer LEAD_UNIT_SDC_ROLE_TYPE_CODE = 28;
//    Integer PROPOSAL_ORTT_ROLE_TYPE_CODE = 415;
//
//    // Variable is used to edit Award Budget fields based on this value
//    String MODIFY_AB_IN_ROUTING = "MODIFY_AB_IN_ROUTING";
//    String ENABLE_CAMPUS_FLAG_AWARD = "ENABLE_CAMPUS_FLAG_AWARD";
//    // Rights
//    String PUBLISH_GRANT_CALL_RIGHT_NAME = "PUBLISH_GRANT_CALL";
//    String MAINTAIN_REVIEW_COMMENTS_RIGHT_NAME = "MAINTAIN_REVIEW_COMMENTS";
//    String MANPOWER_VIEW_BASE_SALARY_RIGHT_NAME = "MANPOWER_VIEW_BASE_SALARY";
//    String VIEW_CONFIDENTIAL_CLAIM_ATTACHMENTS_RIGHT = "VIEW_CONFIDENTIAL_CLAIM_ATTACHMENTS";
//    String VIEW_CONFIDENTIAL_PROGRESS_REPORT_ATTACHMENTS_RIGHT = "VIEW_CONFIDENTIAL_PROGRESS_REPORT_ATTACHMENTS";
//    String VIEW_CONFIDENTIAL_AWARD_ATTACHMENTS_RIGHT = "VIEW_CONFIDENTIAL_AWARD_ATTACHMENTS";
//    String VIEW_CONFIDENTIAL_PROPOSAL_ATTACHMENTS_RIGHT = "VIEW_CONFIDENTIAL_PROPOSAL_ATTACHMENTS";
    String MAINTAIN_DELEGATION_RIGHT_NAME = "MAINTAIN_DELEGATION";
    String MAINTAIN_PERSON_RIGHT_NAME = "MAINTAIN_PERSON";
//    String MODIFY_INST_PROPOSAL = "MODIFY_INST_PROPOSAL";
//
//    // Unit administrator type codes
//    Integer RA_UNIT_ADMINISTRATOR_TYPE_CODE = 1;
//
//    String SIMPLE_EVALUATION_MAP_ID = "SIMPLE_EVALUATION_MAP_ID";
//    String UNIT_ADMINISTRATOR_TYPE_CODE = "1";
//    
//    // Pre review Section type codes
//    String IRB_PRE_REVIEW_SECTION_TYPE_CODE = "8";
//    String PI_PRE_REVIEW_SECTION_TYPE_CODE = "9";
//
//    /// Person Preference
    String PREFERENCE_TYPE_CODE = "101";
//    Integer REVIEW_PROPOSAL_ROLE_ID = 650;
//
//    // Cost Share
//    String SPONSOR = "SPONSOR";
//
//    // Dates And Amounts
//    String EXTERNAL = "EXTERNAL";
//    String INTERNAL = "INTERNAL";
//
//    // Date Formats
    String DEFAULT_DATE_FORMAT = "dd/MM/yyyy";
//    String DEFAULT_DATE_FORMAT_CLAIM = "dd/MM/yy";
//    String REQUIRED_DATE_FORMAT = "dd-MM-yyyy";
//    String EXCEL_DATE_FORMAT = "dd-MMM-yyyy";
//    String EXCEL_LONG_DATE_FORMAT = "dd-MMMM-yyyy";
//    String LONG_DATE_FORMAT = "dd/MM/yyyy HH:mm:ss aa";
    String LOG_DATE_FORMAT = "dd_MM_yyyy";
    String TWELVE_HOUR_DATE_FORMAT = "dd/MM/yyyy hh:mm:ss aa";
//    String ICS_DATE_FORMAT = "yyyy-MM-dd";
//    String PROGRESS_REPORT_DATE_FORMAT = "MMM yyyy";
//    String LOA_DATE_FORMAT = "dd MMMM yyyy";
//    
//    String AWARD_STATUS_ON_APPROVAL = "AWARD_STATUS_ON_APPROVAL";
//
//    String MAIN_PANEL_FOR_SIMPLE_EVALUATION_PANEL = "N";
//
//    String ENABLE_MILESTONE = "ENABLE_MILESTONE";
//    String ENABLE_KEY_PERFORMANCE_INDICATOR = "ENABLE_KEY_PERFORMANCE_INDICATOR";
//    String ENABLE_SCORING_CRITERIA = "ENABLE_SCORING_CRITERIA";
//    String ENABLE_EVALUATION_PANEL = "ENABLE_EVALUATION_PANEL";
//    String ENABLE_SAP_AWARD_FEED = "ENABLE_SAP_AWARD_FEED";
//    String ENABLE_REPLACE_ATTACHMENTS_GRANTCALL = "ENABLE_REPLACE_ATTACHMENTS_GRANTCALL";
//    String ENABLE_REPLACE_ATTACHMENTS_DEV_PROP = "ENABLE_REPLACE_ATTACHMENTS_DEV_PROP";
//    String ENABLE_REPLACE_ATTACHMENTS_IP = "ENABLE_REPLACE_ATTACHMENTS_IP";
//    String ENABLE_REPLACE_ATTACHMENTS_AWARD = "ENABLE_REPLACE_ATTACHMENTS_AWARD";
//    String ENABLE_REPLACE_ATTACHMENTS_NEGOTIATION = "ENABLE_REPLACE_ATTACHMENTS_NEGOTIATION";
//
//    // Action Type code
//    String TASK_ACTION_TYPE_CODE_CREATED = "1";
//    String TASK_ACTION_TYPE_CODE_STARTED = "2";
//    String TASK_ACTION_TYPE_CODE_SUBMITTED = "3";
//    String TASK_ACTION_TYPE_CODE_COMPLETED = "4";
//    String TASK_ACTION_TYPE_CODE_ADDED_COMMENT_ATTACHMENT = "5";
//    String TASK_ACTION_TYPE_CODE_REASSIGNED = "6";
//    String TASK_ACTION_TYPE_CODE_UPDATED = "7";
//    String TASK_ACTION_TYPE_CODE_CANCELLED = "8";
//    String TASK_ACTION_TYPE_CODE_NOTIFIED = "9";
//    String TASK_ACTION_TYPE_CODE_RETURNED = "10";
//    String TASK_ACTION_TYPE_CODE_APPROVED = "11";
//    String TASK_ACTION_TYPE_CODE_BYPASSED = "12";
//    String TASK_ACTION_TYPE_CODE_COMMENT_DELETED = "13";
//
//    // Task Status Code
//    String TASK_STATUS_CODE_OPEN = "1";
//    String TASK_STATUS_CODE_IN_PROGRESS = "2";
//    String TASK_STATUS_CODE_REVIEW_IN_PROGRESS = "3";
//    String TASK_STATUS_CODE_RETURNED = "4";
//    String TASK_STATUS_CODE_COMPLETED = "5";
//    String TASK_STATUS_CODE_CANCELLED = "6";
    String SUBMODULE_ITEM_KEY = "0";
//
//    // Task Type Code
//    String TASK_DMP_TYPE_CODE = "6";
//    String TASK_CONFIRM_PROJECT_DETAILS = "5";
//    String TASK_FINANCE_ACCOUNT_CREATION = "7";
//
//    // Grant Call Abbreviation
//    String IS_GRANTCALL_ABBREVATION_REQUIRED = "IS_GRANTCALL_ABBREVATION_REQUIRED";
//
    String APPLICATION_URL_START_TAG = "<a title=\"\" target=\"_self\" href=";
    String APPLICATION_URL_END_TAG = ">this link</a>";
//    String APPLICATION_URL_AWARD_TASK_PATH = "/fibi/award/task/details?awardId=";
//    String APPLICATION_URL_AWARD_PATH = "/fibi/award/overview?awardId=";
//    String APPLICATION_URL_GRANTCALL_PATH = "/fibi/grant?grantId=";
//    String APPLICATION_URL_PROPOSAL_PATH = "/fibi/proposal?proposalId=";
//    String APPLICATION_URL_NEGOTIATION_PATH = "/fibi/negotiation/negotiationhome?negotiationId=";
//    String SERVICE_REQUEST_APPLICATION_URL_END_TAG = ">View Service Request</a>";
//    String APPLICATION_URL_SERVICE_REQUEST_PATH = "/fibi/service-request/service-request?requestId=";
//    String APPLICATION_URL_CLAIM_PATH = "/fibi/claims/endorsement?claimId=";
//    String APPLICATION_URL_MANPOWER_PATH = "/fibi/award/manpower?awardId=";
//    String APPLICATION_URL_PROGRESS_REPORT_PATH = "/fibi/progress-report/overview?progressReportId=";
    String APPLICATION_URL_PERSON_PATH = "/fibi/person/person-details?personId=";
    String APPLICATION_URL_PERSON_DELEGATION_PATH = "/fibi/person/delegation?personId=";
//    String APPLICATION_URL_AGREEMENT_PATH = "/fibi/agreement/form?agreementId=";
//    String APPLICATION_URL_PROPOSAL_CERTIFIATION_PATH = "/fibi/proposal/certification?proposalId=";
//    String APPLICATION_URL_PROPOSAL_DASHBOARD_PATH = "/fibi/dashboard/proposalList";
//    
//    // Variable types for editable sections
//    String TASK_EDITABLE_SECTION_VARIABLE_TYPE = "T";
//    String VARIATION_REQUEST_VARIABLE_TYPE = "V";
//
//    double PERCENTAGE_EFFORT = 100.00;
//    BigDecimal PERCENTAGE_OF_EFFORT = null;
//
//    // variable type for award budget available funds calculations
//    String ANTICIPATED_TOTAL = "A";
//    String OBLIGATED_DISTRIBUTABLE = "O";
//  
//    // For WBS number generation
//    String ENABLE_AWARD_WBS_GENERATION = "ENABLE_AWARD_WBS_GENERATION";
//    String ENABLE_AWARD_BUDGET_VIREMENT_CALCULATION = "ENABLE_AWARD_BUDGET_VIREMENT_CALCULATION";
//
//    // For IO code generation
//    String ENABLE_AWARD_IO_CODE_GENERATION = "ENABLE_AWARD_IO_CODE_GENERATION";
//
//    // For Manpower Module
//    String IS_MANPOWER_ENABLED = "IS_MANPOWER_ENABLED";
//    String IS_BUDGET_ASSOCIATED_WITH_MANPOWER = "IS_BUDGET_ASSOCIATED_WITH_MANPOWER";
//
//    // manpower sftp for excelity
//    String MANPOWER_SFTP_EXCELITY_EMAIL_RECIPIENT = "MANPOWER_SFTP_EXCELITY_EMAIL_RECIPIENT";
    String SFTP_HOST = "SFTP_HOST";
    String SFTP_PORT = "SFTP_PORT";
    String SFTP_USER = "SFTP_USER";
//    String SFTP_EXCELITY_OUTBOUND = "SFTP_EXCELITY_OUTBOUND";
//    String SFTP_EXCELITY_OUTBOUND_ARCHIVE = "SFTP_EXCELITY_OUTBOUND_ARCHIVE";
//    String IS_EXCELITY_SFTP_ENABLED = "IS_EXCELITY_SFTP_ENABLED";
//    String EXCELITY_PASSPHRASE = "EXCELITY_PASSPHRASE";
//    String PGP_PRIVATE_KEY_PATH = "PGP_PRIVATE_KEY_PATH";
//    String RISE_EXCELITY_OUTBOUND = "RISE_EXCELITY_OUTBOUND";
//    String PGP_DECRYPTED_FILE_PATH = "PGP_DECRYPTED_FILE_PATH";
//    String RISE_EXCELITY_OUTBOUND_ARCHIVE = "RISE_EXCELITY_OUTBOUND_ARCHIVE";
    String SFTP_PASSWORD = "SFTP_PASSWORD";
//    String AES_SECRETE_KEY = "AES_SECRETE_KEY";
//
//    // sap concur
//    String SFTP_SAP_CONCUR_EMAIL_RECIPIENT = "SFTP_SAP_CONCUR_EMAIL_RECIPIENT";
//    String SFTP_SAP_CONCUR_OUTBOUND = "SFTP_SAP_CONCUR_OUTBOUND";
//    String SFTP_SAP_CONCUR_OUTBOUND_ARCHIVE = "SFTP_SAP_CONCUR_OUTBOUND_ARCHIVE";
//    String IS_SAP_CONCUR_ENABLED = "IS_SAP_CONCUR_ENABLED";
//    String RISE_SAP_CONCUR_OUTBOUND = "RISE_SAP_CONCUR_OUTBOUND";
//    String RISE_SAP_CONCUR_OUTBOUND_ARCHIVE = "RISE_SAP_CONCUR_OUTBOUND_ARCHIVE";
//
//    //Base Salary
//    String BASE_SALARY_PGP_DECRYPTED_FILE_PATH = "BASE_SALARY_PGP_DECRYPTED_FILE_PATH";
//    String SFTP_BASE_SALARY_EMAIL_RECIPIENT = "SFTP_BASE_SALARY_EMAIL_RECIPIENT";
//    String IS_BASE_SALARY_ENABLED = "IS_BASE_SALARY_ENABLED";
//    String BASE_SALARY_PASSPHRASE = "BASE_SALARY_PASSPHRASE";
//    String PGP_BASE_SALARY_PRIVATE_KEY_PATH = "PGP_BASE_SALARY_PRIVATE_KEY_PATH";
//    String SFTP_BASE_SALARY_OUTBOUND = "SFTP_BASE_SALARY_OUTBOUND";
//    String SFTP_BASE_SALARY_OUTBOUND_ARCHIVE = "SFTP_BASE_SALARY_OUTBOUND_ARCHIVE";
//    String RISE_BASE_SALARY_OUTBOUND = "RISE_BASE_SALARY_OUTBOUND";
//    String RISE_BASE_SALARY_OUTBOUND_ARCHIVE = "RISE_BASE_SALARY_OUTBOUND_ARCHIVE";
//
    // Number format
    String NUMBER_FORMAT_WITH_DECIMAL = "#,###,##0.00";
    String NUMBER_FORMAT_WITHOUT_DECIMAL = "#,###";
//
//    // Symbols
//    String DOLLAR_SYMBOL = "$";
//    String NUMBER_FORMAT = "#,###,##";
//
    String YES = "Y";
    String NO = "N";
    String EXPIRED = "E";
//
//    String SINGAPORE_NUMBER_FORMAT_WITH_DECIMAL = "#,###,##0.00";
//
//    // fast Integration
//    String FAST_INTEGRATION_FILE_DATE_FORMAT = "ddMMyyyy";
//    String FAST_INTEGRATION_LOG_DATE_FORMAT = "yyyyMMdd";
//    String FAST_INTEGRATION_EMAIL_RECIPIENT = "FAST_INTEGRATION_EMAIL_RECIPIENT";
//    String ENABLE_FAST_INTEGRATION_EMAIL = "ENABLE_FAST_INTEGRATION_EMAIL";
//    
//    String RISE_FAST_INBOUND = "RISE_FAST_INBOUND";
//    String SFTP_FAST_INBOUND = "SFTP_FAST_INBOUND";
//    String FAST_LOG_FILE_PATH = "FAST_LOG_FILE_PATH";
//    String RISE_FAST_OUTBOUND_RESPONSE = "RISE_FAST_OUTBOUND_RESPONSE";
//    String RISE_FAST_OUTBOUND_ARCHIVE_RESPONSE = "RISE_FAST_OUTBOUND_ARCHIVE_RESPONSE";
//    String SFTP_FAST_OUTBOUND_RESPONSES = "SFTP_FAST_OUTBOUND_RESPONSES";
//    String SFTP_FAST_OUTBOUND_RESPONSE_ARCHIVE = "SFTP_FAST_OUTBOUND_RESPONSE_ARCHIVE";    
//    String RISE_FAST_OUTBOUND_ARCHIVE_EXPENSE = "RISE_FAST_OUTBOUND_ARCHIVE_EXPENSE"; 
//    String SFTP_FAST_OUTBOUND_EXPENSES = "SFTP_FAST_OUTBOUND_EXPENSES";
//    String SFTP_FAST_OUTBOUND_EXPENSES_ARCHIVE = "SFTP_FAST_OUTBOUND_EXPENSES_ARCHIVE";
//    String RISE_FAST_OUTBOUND_EXPENSES = "RISE_FAST_OUTBOUND_EXPENSES";
//
//    String SAP_FEED_INBOUND_ARCHIVE = "SAP_FEED_INBOUND_ARCHIVE";
//    String SFTP_REVENUE_OUTBOUND = "SFTP_REVENUE_OUTBOUND";
//    String SFTP_REVENUE_OUTBOUND_ARCHIVE = "SFTP_REVENUE_OUTBOUND_ARCHIVE";
//    String RISE_REVENUE_OUTBOUND = "RISE_REVENUE_OUTBOUND";
//    String RISE_REVENUE_INVOICE_OUTBOUND = "RISE_REVENUE_INVOICE_OUTBOUND";
//    String SFTP_REVENUE_INVOICE_OUTBOUND = "SFTP_REVENUE_INVOICE_OUTBOUND";
//    String SFTP_REVENUE_INVOICE_OUTBOUND_ARCHIVE = "SFTP_REVENUE_INVOICE_OUTBOUND_ARCHIVE";
//    String RISE_REVENUE_INVOICE_OUTBOUND_ARCHIVE = "RISE_REVENUE_INVOICE_OUTBOUND_ARCHIVE";
//    String RISE_REVENUE_OUTBOUND_ARCHIVE = "RISE_REVENUE_OUTBOUND_ARCHIVE";
//    String RISE_CLAIM_INVOICE_INBOUND = "RISE_CLAIM_INVOICE_INBOUND";
//    String SFTP_INVOICE_INBOUND_FILE_PATH = "SFTP_CLAIM_INVOICE_INBOUND";
//    String SFTP_CLAIM_INVOICE_OUTBOUND = "SFTP_CLAIM_INVOICE_OUTBOUND";
//    String SFTP_CLAIM_INVOICE_OUTBOUND_ARCHIVE = "SFTP_CLAIM_INVOICE_OUTBOUND_ARCHIVE";
//    String RISE_CLAIM_INVOICE_OUTBOUND = "RISE_CLAIM_INVOICE_OUTBOUND";
//    String RISE_CLAIM_INVOICE_OUTBOUND_ARCHIVE = "RISE_CLAIM_INVOICE_OUTBOUND_ARCHIVE";
    String RISE_EXTERNAL_USER_FEED = "RISE_EXTERNAL_USER_FEED";
    String SFTP_EXTERNAL_USER_FEED_EMAIL_RECIPIENT = "SFTP_EXTERNAL_USER_FEED_EMAIL_RECIPIENT";
//
//    String PERSON_FEED_API_ENABLE = "PERSON_FEED_API_ENABLE";
//    String STUDENT_FEED_API_ENABLE = "STUDENT_FEED_API_ENABLE";
//    String STAFF_API_FLAG = "STAFF_API_FLAG";
//    String STUDENTS_API_FLAG = "STUDENTS_API_FLAG";
//    String IS_SFTP_ENABLED = "IS_SFTP_ENABLED";
//
//    // Role id
//    Integer PI_RESEARCH_ASSISTANTS = 618;
//    Integer CREATE_PROPOSAL = 4;
//
//    // for waf
//    String IS_WAF_ENABLED = "IS_WAF_ENABLED";
//
    String CRON_JOB_TIMEZONE = "Asia/Singapore";
//    String BUDGET_ASSOCIATED_WITH_NON_PERSONAL_SUBITEM_ENABLED = "BUDGET_ASSOCIATED_WITH_NON_PERSONAL_SUBITEM_ENABLED";
//    String LOGIN_FLAG = "IN";
//    String LOGOUT_FLAG = "OUT";
//    String START_TIME = "00:00:00.0";
    String END_TIME = "23:59:59.0";
//    String TIME_FORMAT = "HH:mm:ss";
//
//    // GrantCall Action Type Code
//    String GRANT_CALL_CREATED = "1";
//    String GRANT_CALL_PUBLISHED = "2";
//    String GRANT_CALL_UPDATED = "3";
//    String DEFAULT_BUDGET_DATE_FORMAT = "yyyy-MM-dd hh:mm:ss.SSS";
//
//    // for Organization
//    String ENABLE_USER_DEFINED_ORGANIZATION = "ENABLE_USER_DEFINED_ORGANIZATION";
//
//    String SAP_AWARD_FEED_ERROR_TYPE = "GRANT_CODE_ERROR";
//
//    String IS_ORCID_WORK_ENABLED = "IS_ORCID_WORK_ENABLED";
//
//    String AUTOMATE_GRANTCALL_INTERNAL_STATUS = "AUTOMATE_GRANTCALL_INTERNAL_STATUS";
//
//    // hide special review
//    String ENABLE_SPECIAL_REVIEW = "ENABLE_SPECIAL_REVIEW";
//    String SPECIAL_REVIEW_SECTION_TYPE_CODE = "113";
//    String SPECIAL_REVIEW_IRB_TYPE_CODE = "1";
//    String SPECIAL_REVIEW_AC_TYPE_CODE = "2";
//    String BUDGET_EDITABLE_SECTION_TYPE_CODE = "102";
//    String REPORT_REQ_EDITABLE_SECTION_TYPE_CODE = "109";
//    String DATES_AND_AMOUNT_EDITABLE_SECTION_TYPE_CODE = "108";
//    String NIE_BUSINESS_AREA_CODE = "A640";
//    String LKC_BUSINESS_AREA_CODE = "A630";
//    String RSIS_BUSINESS_AREA_CODE = "A650";
//    String SAP_EMAIL_NIE_ADDRESS = "SAP_EMAIL_NIE_ADDRESS";
//    String SAP_EMAIL_LKC_ADDRESS = "SAP_EMAIL_LKC_ADDRESS";
//    String SAP_EMAIL_RSIS_ADDRESS = "SAP_EMAIL_RSIS_ADDRESS";
//    String SAP_EMAIL_NTU_ADDRESS = "SAP_EMAIL_NTU_ADDRESS";
//    String FAST_INTEGRATION_EMAIL_CC_ADDRESS = "FAST_INTEGRATION_EMAIL_CC_ADDRESS";
//
//    // Manpower
//    String MANPOWER_BUDGET_REFERENCE_WBS_TYPE = "1";
//    String MANPOWER_BUDGET_REFERENCE_AWARD_BUDGET_DETIAL_TYPE = "2";
//    String MANPOWER_TYPE_STUDENT = "2";
//    String MANPOWER_TYPE_STAFF = "1";
//    String MANPOWER_TYPE_OTHER = "3";
//
//    String MANPOWER_POSITION_NOT_TRIGGERED = "1";
//    String MANPOWER_READY_TO_TRIGGER_POSITION = "2";
//    String MANPOWER_POSITION_GENERATED = "3";
//    String MANPOWER_ACTIVE = "6";
//    String MANPOWER_ENDED = "5";
//    String MANPOWER_PENDING_APPROVAL = "4";
//    String MANPOWER_EXPIRED = "8";
//    String MANPOWER_FAILED_POSITION_GENERATED = "9";
//    String POSITION_UPDATED_BY_ADMIN_CORRECTION = "10";
//    String MANPOWER_INACTIVE = "11";
//
//    String NEW_MANPOWER = "New";
//    String OTHER_MANPOWER = "Other";
//    
//    String MANPOWER_RESOURCE_MULTIPLIER = "Multiplier %";
//    String CUSTOM_DATA_LEVEL_2_SUP_ORG = "Level_2_Sup_Org";
//    String MANPOWER_INTERFACE_POSITION_CREATION = "1";
//    String MANPOWER_INTERFACE_COST_ALLOCATION = "2";
//    String MANPOWER_INTERFACE_CHECK_PI_SUP_ORG = "5";
//    String MANPOWER_INTERFACE_CREATE_SUP_ORG = "6";
//    String MANPOWER_INTERFACE_ASSIGN_ROLES = "7";
//    String MANPOWER_INTERFACE_HRBP = "14";
//    String MANPOWER_INTERFACE_MOVE_WORKERS = "8";
//    String MANPOWER_INTERFACE_MANPOWER_DETAILS = "9";
//    String MANPOWER_INTERFACE_CITIZENSHIP_NATIONALITY = "10";
//    String MANPOWER_INTERFACE_JOB_PROFILE = "16";
//    String MANPOWER_INTERFACE_LONG_LEAVE = "12";
//    String MANPOWER_INTERFACE_TERMINATION_AND_RESIGNATION = "13";
//    String MANPOWER_INTERFACE_DESIGNATION_CHANGE = "15";
//    String MANPOWER_INTERFACE_JOB_REQUISITION = "18";
//
//    String MANPOWER_INTERFACE_SUCCESS = "1";
//    String MANPOWER_INTERFACE_ERROR = "2";
//    String MANPOWER_INTERFACE_PENDING = "3";
//    String MANPOWER_INTERFACE_FEED_NOT_NEEDED = "4";
//    String MANPOWER_INTERFACE_RETRIGGERED = "5";
//    String MANPOWER_INTERFACE_COST_RECONCILIATION = "11";
//    String MANPOWER_COST_ALLOCATION_CUT_OFF_DATE = "MANPOWER_COST_ALLOCATION_CUT_OFF_DATE";
//    String MANPOWER_INFO_TEXT = "MANPOWER_INFO_TEXT";
//    String MANPOWER_ADMIN_CORRECTION_PLAN_START_DATE_BUFFER = "MANPOWER_ADMIN_CORRECTION_PLAN_START_DATE_BUFFER";
//    String MANPOWER_POSITION_REGEX = "MANPOWER_POSITION_REGEX";
//
//    String MANPOWER_MESSAGE_TYPE = "SUCCESS";
//    String MANPOWER_RE_TRIGGER = "1";
//    String MANPOWER_MANUAL_PROCESS = "2";
//
//    String WORKDAY_SUBSCRIPTION_KEY_NAME = "Ocp-Apim-Subscription-Key";
//    String WORKDAY_API = "WORKDAY_API";
//    String WORKDAY_SUBSCRIPTION_KEY_VALUE = "SUBSCRIPTION_KEY_VALUE";
//    String WORKDAY_USERNAME = "Rise_Workday@ntu";
//    String WORKDAY_PASSWORD = "S@CuR!T%2020";
//    String WOKRDAY_LONG_LEAVE_TRIGGER_DATE_DIFFERENCE = "WOKRDAY_LONG_LEAVE_TRIGGER_DATE";
//    String WORKDAY_TERMINATION_TRIGGER_DATE_DIFFERENCE = "WORKDAY_TERMINATION_TRIGGER_DATE";
//    String COSTING_ALLOCATION_END_DATE = "COSTING_ALLOCATION_END_DATE";
//    String MIGRATION_END_DATE = "MIGRATION_END_DATE";
//    String IS_MANPOWER_WORKDAY_LOG_NEEDED = "IS_MANPOWER_WORKDAY_LOG_NEEDED";
//    String PERSON_INACTIVE_THRESHOLD = "PERSON_INACTIVE_THRESHOLD";
//    String WORKDAY_EFFECTIVE_AS_OF_DATE = "WORKDAY_EFFECTIVE_AS_OF_DATE";
//    String WORKDAY_RECONCILATION_START_DATE = "WORKDAY_RECONCILATION_START_DATE";
//    
//    // Claim
//    String CLAIM_STATUS_CODE_PENDING = "1";
//    String CLAIM_STATUS_CODE_REVISION = "2";
//    String CLAIM_STATUS_CODE_APPROVAL_IN_PROGRESS = "3";
//    String CLAIM_STATUS_CODE_COMPLETED = "4";
//    String CLAIM_STATUS_CODE_APPROVED = "5";
//    String CLAIM_STATUS_CODE_SUBMITTED_FOR_FA = "6";
//    String CLAIM_STATUS_CODE_REVISION_BY_FA = "7";
//    String CLAIM_STATUS_CODE_APPROVED_BY_FA = "8";
//    String CLAIM_GENERIC_EXCEL_LETTER_TEMPLATE_TYPE = "900";
//    String CLAIM_IGMS_TEMPLATE_TYPE = "904";
//    String CLAIM_ASTAR_ACTUAL_TEMPLATE_TYPE = "905";
//    String CLAIM_ASTAR_COMMITTED_TEMPLATE_OOE = "909";
//    String CLAIM_ASTAR_COMMITTED_TEMPLATE_EQPT = "910";
//    String SUBMIT_FOR_FA_REVIEW = "S";
//    String REVISION_REQ_FA_REVIEW = "R";
//    String APPROVED_BY_FA_REVIEW = "A";
//    String CLAIM_FORECAST_TEMPLATE = "800";
//    String CLAIM_MAINTAIN_DETAILED_BREAKDOWN = "CLAIM_MAINTAIN_DETAILED_BREAKDOWN";
//    String TRIGGER_INVOICE = "T";
//    String CLAIM_STATUS_CODE_INVOICE_TRIGGERED = "9";
//    String CLAIM_STATUS_CODE_INVOICE_GENERATED = "10";
//    String CLAIM_STATUS_CODE_INVOICE_NOT_GENERATED = "11";
//	String CLAIM_FEED_TYPE_CREDIT = "1";
//    String CLAIM_TEMPLATE = "CLAIM_TEMPLATE";
//    String CLAIM_EXPORT_ERR_MSG = "There is no template(s) is mapped for claim export. Please check the award and update claim template in the other Information tab";
//
//    // Parameter to indicate whether custom data needs to copy or not
//    String IS_COPY_CUSTOM_DATA = "IS_COPY_CUSTOM_DATA";
//
//    String PROPOSAL_CREATE_USER_AS_PI_BY_DEFAULT = "PROPOSAL_CREATE_USER_AS_PI_BY_DEFAULT";
//    String VIEW_PRIVATE_COMMENTS_RIGHT = "VIEW_PRIVATE_COMMENTS";
//    String MAINTAIN_PRIVATE_COMMENTS = "MAINTAIN_PRIVATE_COMMENTS";
//    String VIEW_PROPOSAL_RIGHT = "VIEW_PROPOSAL";

    String CUSTOM_DATA_TYPE_CHECKBOX = "4";

//    //AWARD Amount Transaction Status
//    String ACTIVE_TRANSACTION = "A";
//    String PENDING_TRANSACTION = "P";
//    String CANCELLED_TRANSACTION = "V";
//
//    String AWARD_KEY_PERSON_TIMESHEET_TYPE = "AWARD_KEY_PERSON_TIMESHEET_TYPE";
//
//    // Sap Feed Status
//    String SAP_FEED_STATUS_SUCCESS = "R";
//    String SAP_FEED_STATUS_ERROR = "E";
//    String SAP_FEED_STATUS_PENDING = "P";
//    String SAP_FEED_STATUS_NONE_TO_FEED = "N";
//    String SAP_FEED_STATUS_FEED = "F";
//    String SAP_FEED_STATUS_CANCELLED = "X";
//    String SAP_FEED_TYPE_NEW = "N";
//    String SAP_FEED_USER_ACTION_QUEUE_TO_FEED = "7";
//    String SAP_FEED_STATUS_CONCURRENT = "C";
//    String SAP_FEED_STATUS_HOLD = "H";
//    String SAP_FEED_STATUS_CONCURRENT_HOLD = "CH";
//    String SAP_FEED_STATUS_CONCURRENT_CANCELLED = "CX";
//
//    String BATCH_DETAIL = "BATCH_DETAIL";
//    String PENDING_FEED = "PENDING_FEED";
//    String CANCEL_FEED_TAB = "C";
//    String HOLD_FEED = "H";
//    String QUE_TO_FEED_TAB = "Q";
//    String UPDATE_FEED_STATUS_TAB = "U";
//
//    //Progress report
//    String PROGRESS_REPORT_STATUS_CODE_PENDING = "1";
//    String PROGRESS_REPORT_STATUS_CODE_REVISION = "2";
//    String PROGRESS_REPORT_STATUS_CODE_APPROVAL_IN_PROGRESS = "3";
//    String PROGRESS_REPORT_STATUS_CODE_APPROVED = "4";
//    String PROGRESS_REPORT_STATUS_CODE_HOLD_FOR_FA = "5";
//    String PROGRESS_REPORT_STATUS_CODE_COMPLETED = "6";
//    String HOLD_FOR_FA_REVIEW = "H";
//    String FA_REVIEW_COMPLETED = "C";
//    String PROGRESSREPORTKPIIMPACTPUBLICATIONS = "ProgressReportKPIImpactPublications";
//    String PROGRESSREPORTKPICOLLABORATIONPROJECTS = "ProgressReportKPICollaborationProjects";
//    String PROGRESSREPORTKPITECHNOLOGYDISCLOSURE = "ProgressReportKPITechnologyDisclosure";
//    String PROGRESSREPORTKPIMANPOWERDEVELOPMENT = "ProgressReportKPIManpowerDevelopment";
//    String PROGRESSREPORTKPIUNDERGRADUATESTUDENT = "ProgressReportKPIUndergraduateStudent";
//    String PROGRESSREPORTKPICONFERENCEPRESENTATION = "ProgressReportKPIConferencePresentation";
//    String PROGRESSREPORTKPICOMPETITIVEGRANTS = "ProgressReportKPICompetitiveGrants";
//    String PROGRESSREPORTKPIPATENTS = "ProgressReportKPIPatents";
//    String PROGRESSREPORTKPILICENSES = "ProgressReportKPILicenses";
//    String PROGRESSREPORTKPISUCCESSFULSTARTUPS = "ProgressReportKPISuccessfulStartups";
//    String PROGRESSREPORTKPIHEALTHSPECIFICOUTCOMES = "ProgressReportKPIHealthSpecificOutcomes";
//    String PROGRESSREPORTKPIPOSTDOCSEMPLOYED = "ProgressReportKPIPostDocsEmployed";
//    String PROGRESSREPORTKPIGRANTSPECIFIC = "ProgressReportKPIGrantSpecific";
//    String PROGRESSREPORTKPICASHFUNDING = "ProgressReportKPICashFunding";
//    String PROGRESSREPORTKPITECHNOLOGIESDEPLOYED = "ProgressReportKPITechnologiesDeployed";
//    String PROGRESSREPORTKPIINKINDCONTRIBUTIONS = "ProgressReportKPIInkindContributions";
//    String PROGRSS_REPORT_QUESTIONNAIRE_LETTER_TEMPLATE_TYPE_CODE = "120";
//    String PROGRESS_REPORT_CLASS_CODE = "1";
//    String FINAL_REPORT_CLASS_CODE = "2";
//    String FREQUENCY_BASE_PROJECT_END_DATE = "4";
//    String PROGRESS_REPORT_SECTION_TYPE_FUTURE = "F";
//    String PROGRESS_REPORT_SECTION_TYPE_SUMMARY = "S";
//    String CREATE_PROGRESS_REPORT = "CREATE_PROGRESS_REPORT";
//
//    String MANPOWER_EDITABLE_FIELD = "131";
//    String MANPOWER_TRIGGER_RESOURCE_EDITABLE_FIELD = "133";
//    String AWARD_OVERVIEW_EDITABLE_FIELD = "101";
//    String AWARD_KEY_PERSONNEL_EDITABLE_FIELD = "104";
//    String AWARD_CUSTOM_DATA_EDITABLE_FIELD = "120";
//    String AWARD_PROGRESS_REPORT_ENABLED = "AWARD_PROGRESS_REPORT_ENABLED";
//
//    String ACTIVE_PERSON = "A";
//    String MANPOWER_LOG_MESSAGE_TYPE = "ERROR";
//    String CLAIM_TEMPLATE_EXPENSE_COMMITMENT_VALUE = "E";
//    String ENABLE_LINK_AWARD_IN_PROPOSAL = "ENABLE_LINK_AWARD_IN_PROPOSAL";
//    String ENABLE_PROPOSAL_ORGANIZATION = "ENABLE_PROPOSAL_ORGANIZATION";
//    String ENABLE_CAMPUS_FLAG_PROPOSAL = "ENABLE_CAMPUS_FLAG_PROPOSAL";
//
//    String GRANT_CALL_POC_DEFAULT_EMAIL = "GRANT_CALL_POC_DEFAULT_EMAIL";
//
    String DELEGATION_REQUESTED_STATUS = "R";
    String DELEGATION_ACCEPTED_STATUS = "A";
    String DELEGATION_DELETE_STATUS = "X";
    String DELEGATION_DENIED_STATUS = "D";
//    String ENABLE_ADD_TO_ADDRESS_BOOK = "ENABLE_ADD_TO_ADDRESS_BOOK";
//
    String REPORT_FOOTER = "Confidential";
    String REPORT_HEADER = "FIBI Research Administration Suite Report";

    //PDF Header and Footer positions
    Integer IMAGE_X_POSITION = 100;
    Integer IMAGE_Y_POSITION = 530;
    Integer HEADER_Y_POSITION = 570;
//
//    String ENABLE_USER_DEFINED_FUNDING_AGENCY = "ENABLE_USER_DEFINED_FUNDING_AGENCY";
//
//    //Administrative Report type
//    String ROLE_MASTER_DATA = "ROLE_MASTER_DATA";
//    String ROLE_RIGHT_MAPPING = "ROLE_RIGHT_MAPPING";
//    String PERSON_ROLE_ASSIGNMENT = "PERSON_ROLE_ASSIGNMENT";
//    String UNIT_HIERARCHY = "UNIT_HIERARCHY";
//    String UNIT_ADMINISTRATOR_HOD = "UNIT_ADMINISTRATOR_HOD";
//    String BUDGET_COST_ELEMENT_MASTER_DATA = "BUDGET_COST_ELEMENT_MASTER_DATA";
//    String ROLODEX_MASTER_DATA = "ROLODEX_MASTER_DATA";
//    String SPONSOR_MASTER_DATA = "SPONSOR_MASTER_DATA";
//    String ORGANIZATION_MASTER_DATA = "ORGANIZATION_MASTER_DATA";
//
//    // External User acceptance code
    String PENDING_USER = "P";
    String APPROVED_USER = "A";
    String REJECTED_USER = "R";
    String DEACTIVATED_USER = "D";
    String EXTERNAL_USER_FLAG = "Y";
    String INACTIVE_USER = "I";
    String ADD = "ADD";
    String DELETE = "DELETE";
    String EXTERNAL_USER_FEED_STATUS = "F";
    String EXTERNAL_USER_MAIL_SENT = "S";
//    // 	External User
    String EXTERNAL_USER_HOME_UNIT = "9999";
//    //Proposal Document Status
//    String PROPOSAL_DOCUMENT_STATUS_ACTIVE = "1";
//    String PROPOSAL_DOCUMENT_STATUS_ADMIN_CORRECTION = "2";
//    String PROPOSAL_DOCUMENT_STATUS_ARCHIVE = "3";
//	
//    String PROPOSAL_ADMIN_CORRECTION = "Admin Correction";
//    String PROPOSAL_RETURNED = "Revision Requested";
//    String ARCHIVE_TYPE_PROPOSAL = "ProposalArchive";
//    String ENABLE_DEV_PROP_VERSIONS = "ENABLE_DEV_PROP_VERSIONS";
//    String MAINTAIN_EXTERNAL_USER = "MAINTAIN_EXTERNAL_USER";
    String EXTERNAL_USER_PASSWORD_RESET_LINK = "EXTERNAL_USER_PASSWORD_RESET_LINK";
    String EXTERNAL_USER_SIGNIN_LINK = "EXTERNAL_USER_SIGNIN_LINK";

    Integer EXTERNAL_USER_ACCESS = 350;
//    String MAINTAIN_SAP_FEED = "MAINTAIN_SAP_FEED";
//    String MAINTAIN_INVOICE_FEED = "MAINTAIN_INVOICE_FEED";
//    String MAINTAIN_INVOICE_INTERFACE_PROCESSING = "MAINTAIN_INVOICE_INTERFACE_PROCESSING";
//    String GRANTCALL_ELIGIBLE_TARGET_TYPE_MAILING_LIST = "GRANTCALL_ELIGIBLE_TARGET_TYPE_MAILING_LIST";
//    String ENABLE_OVERHEAD_RATE_TYPE = "ENABLE_OVERHEAD_RATE_TYPE";
//
//    //Scopus
//    String SCOPUS_DYN_SUBSECTION_CODE = "195";
//    String SCOPUS_API = "SCOPUS_API";
//    String SCOPUS_SCIVAL_API = "SCIVAL_API";
//    String SCOPUS_SCIVAL_API_EXTEND1 = "SCIVAL_API_EXTEND1";
//    String SCOPUS_SCIVAL_API_EXTEND2 = "SCIVAL_API_EXTEND2";
//    
//    
//    Integer READY_TO_EXECUTE_NOTIFICATION_CODE = 718;
//    Integer AGREEMENT_FINAL_NOTIFICATION_CODE = 719;
//    Integer AGREEMENT_ASSIGN_ADMIN_NOTIFICATION_CODE = 720;
//    Integer AGREEMENT_ASSIGN_ADMIN_GROUP_NOTIFICATION_CODE = 721;
//    Integer ACTION_LOG_AGREEMENT_TRANSFERRED_NOTIFICATION_CODE = 1421;
//    Integer ACTION_LOG_AGREEMENT_TERMINATED_NOTIFICATION_CODE = 1422;
//    Integer ACTION_LOG_AGREEMENT_ABANDONED_NOTIFICATION_CODE = 1423;
//    Integer ACTION_LOG_AGREEMENT_COMPLETE_REVIEW_NOTIFICATION_CODE = 1424;
//    Integer ACTION_LOG_AGREEMENT_PUT_ON_HOLD_NOTIFICATION_CODE = 1425;
//    Integer ACTION_LOG_AGREEMENT_SET_INPROGRESS_NOTIFICATION_CODE = 1426;
//    Integer ACTION_LOG_AGREEMENT_HOD_REVIEW_INPROGRESS_NOTIFICATION_CODE = 1427;
//    Integer ACTION_LOG_AGREEMENT_LEGAL_REVIEW_INPROGRESS_NOTIFICATION_CODE = 1428;
//    Integer ACTION_LOG_AGREEMENT_SUBMIT_TO_OTHER_PARTY_NOTIFICATION_CODE = 1429;
//
    String ADMIN_GROUP_RIGHT = "VIEW_ADMIN_GROUP_AGREEMENT";
//
//    // Agreement history messages for various actions
//    String LOCATION_ASSIGN_START_MESSAGE = "Agreement application has been sent to ";
//    String LOCATION_ASSIGN_END_MESSAGE = " for review ";
//    String LOCATION_COMPLETE_START_MESSAGE = "Agreement application review completed at ";
//
//    //Location Statuses
//    String LOCATION_ASSIGNED = "1";
//    String LOCATION_INPROGRESS = "2";
//    String LOCATION_COMPLETED = "3";
//
//    //Triage
//    String TRIAGE_STATUS_PENDING = "PENDING";
//    String TRIAGE_STATUS_CREATED = "CREATED";
//    String TRIAGE_STATUS_NA = "NA";
//    Integer TRIAGE_SUB_MODULE_CODE = 999;
//    String IS_TRIAGE_QUESTIONNAIRE_REQUIRED  = "IS_TRIAGE_QUESTIONNAIRE_ENABLE";
//
    String PLACEHOLDER_AGREEMENT = "PLACEHOLDER_AGREEMENT";
//
//    String AGREEMENT_REPORT_TEMPLATE_NAME = "-KKI";
//
//    String IS_ENABLE_CREATE_AGREEMENT = "IS_ENABLE_CREATE_AGREEMENT";
//    String IS_ENABLE_AGREEMENT_SUPPORT = "IS_ENABLE_AGREEMENT_SUPPORT";
//    String IS_ENABLE_AGREEMENT_NOTIFY_ACTION = "IS_ENABLE_AGREEMENT_NOTIFY_ACTION";
//
//    String SHOW_AWARD_MILESTONE_STATUS = "SHOW_AWARD_MILESTONE_STATUS_UPDATE";
//
//    String AGREEMENT_QUESTIONNAIRE_LETTER_TEMPLATE_TYPE_CODE = "501";
//
//    // award submodules
//    Integer AWARD_PROJECT_CLOSURE_SUBMODULE_CODE = 6;
//    Integer AWARD_SUMBIT_CLOSURE_SUBMODULE_CODE = 5;
//    String SUBMIT_CLOSURE_TYPE_CODE = "21";
//    
//
//    //Agreement Roles
    Integer AGREEMENT_ADMINISTRATOR = 1300;
    Integer VIEW_ADMIN_GROUP_AGREEMENT = 1303;
//
//    // Agreement attachment type codes
//    String ATTACHMENT_TYPE_CODE_GENERATE_AGREEMENT = "4";
//    // Agreement Status
//    String AGREEMENT_STATUS_INPROGRESS = "1";
//    String AGREEMENT_STATUS_REVIEW_INPROGRESS = "2";
//    String AGREEMENT_STATUS_EXECUTED = "3";
//    String AGREEMENT_STATUS_RETURNED = "6";
//    String AGREEMENT_STATUS_FINAL = "4";
//    String AGREEMENT_STATUS_ROUTING = "5";
//    String AGREEMENT_STATUS_SUBMITTED = "7";
//    String AGREEMENT_STATUS_TRASFERRED = "8";
//    String AGREEMENT_STATUS_TERMINATED = "9";
//    String AGREEMENT_STATUS_ABANDONED = "10";
//    //String AGREEMENT_STATUS_REOPEN = "11";
//
//    Integer CONTRACT_ADMIN_TYPE_ID = 7;
//    String PRIME_SPONSOR_ROLE = "5";
//    String SPONSOR_TYPE_OTHER = "2";
//
//    Boolean IMPORT_PI_DETAILS = true;
//    Boolean IMPORT_SPONSOR_DETAILS = true;
//    Boolean IMPORT_CA_DETAILS = true;
//    Boolean IMPORT_PRIME_SPONSOR_DETAILS = true;
//
//    Integer AGREEMENT_MODULE_CODE = 13;
//    // Negotiation WF Status
//    String NEGOTIATION_WORKFLOW_INPROGRESS = "1";
//    // Agreement Association type codes
//    String AGREEMENT_ASSOCIATION_TYPE = "4";
//    Integer AGREEMENT_SUBMODULE_CODE = 0;
//    // Message Type code
//    String MESSAGE_TYPE_LOCATION_ASSIGNMENT = "1300";
//    String MESSAGE_TYPE_SENT_TO_THIRD_PARTY = "1301";
//    String MESSAGE_TYPE_SENT_TO_LEGAL = "1302";
//    String MESSAGE_TYPE_SENT_TO_HOD = "1303";
//    String MESSAGE_TYPE_SUBMITTED = "1304";
//    String MESSAGE_TYPE_LEGAL_COMPLETED = "1305";
//    String MESSAGE_TYPE_THIRD_PARTY_COMPLETED = "1306";
//    String MESSAGE_TYPE_HOD_COMPLETED = "1307";
//    String MESSAGE_TYPE_ROUTING_IN_PROGRESS = "1308";
//    String MESSAGE_TYPE_RETURNED = "1309";
//      // Agreement WF Status
//    String AGREEMENT_WORKFLOW_THIRD_PARTY_INPROGRESS = "1";
//    String AGREEMENT_WORKFLOW_LEGAL_INPROGRESS = "2";
//    String AGREEMENT_WORKFLOW_HOD_INPROGRESS = "3";
//    String AGREEMENT_WORKFLOW_THIRD_PARTY_COMPLETED = "4";
//    String AGREEMENT_WORKFLOW_LEGAL_COMPLETED = "5";
//    String AGREEMENT_WORKFLOW_HOD_COMPLETED = "6";
//    String AGREEMENT_WORKFLOW_INPROGRESS = "7";
//    String AGREEMENT_WORKFLOW_COMPLETED = "8";
//    String AGREEMENT_WORKFLOW_ON_HOLD = "9";
//    String AGREEMENT_WORKFLOW_SUBMIT_TO_OTHER_PARTY = "10";
//    String AGREEMENT_WORKFLOW_SUBMIT_TO_OGC = "11";
//    String AGREEMENT_WORKFLOW_SUBMIT_TO_RAS = "12";
//    String AGREEMENT_WORKFLOW_SUBMIT_TO_TLO = "13";
//
//    String SUBMIT_AGREEMENT_EMAIL = "SUBMIT_AGREEMENT_EMAIL";
//    // Agreement Action Log Status
//    String ACTION_LOG_AGREEMENT_CREATED = "1";
//    String ACTION_LOG_AGREEMENT_SUBMITTED = "2";
//    String ACTION_LOG_EXECUTED = "7";
//    String ACTION_LOG_GENERATE_AGREEMENT = "8";
//    String ACTION_LOG_REGENERATE_AGRREMENT = "9";
//    String ACTION_LOG_REPLACE_AGREEMENT = "10";
//    String ACTION_LOG_LOCATION_ASSIGN = "11";
//    String ACTION_LOG_LOCATION_COMPLETE = "12";
//    String ACTION_LOG_FINAL_AGREEMENT = "13";
//    String ACTION_LOG_AGREEMENT_SENT_TO_SPONSOR = "14";
//    String ACTION_LOG_AGREEMENT_LEGAL_REVIEW_INPROGRESS = "15";
//    String ACTION_LOG_AGREEMENT_HOD_REVIEW_INPROGRESS = "16";
//    String ACTION_LOG_AGREEMENT_COMPLETED_SPONSOR = "17";
//    String ACTION_LOG_AGREEMENT_LEGAL_COMPLETED = "18";
//    String ACTION_LOG_AGREEMENT_HOD_COMPLETED = "19";
//    String ACTION_LOG_AGREEMENT_ROUTING = "20";
//    String ACTION_LOG_AGREEMENT_ROUTING_COMPLETED = "21";
//    String ACTION_LOG_AGREEMENT_ROUTING_RETURNED = "22";
//    String ACTION_LOG_ASSIGNED_TO_ADMIN = "23";
//    String ACTION_LOG_REASSIGNED_TO_ADMIN = "24";
//    String ACTION_LOG_AGREEMENT_PUT_ON_HOLD = "25";
//    String ACTION_LOG_AGREEMENT_SUBMIT_TO_OTHER_PARTY = "26";
//    String ACTION_LOG_AGREEMENT_SUBMIT_TO_OGC = "27";
//    String ACTION_LOG_AGREEMENT_SUBMIT_TO_RAS = "28";
//    String ACTION_LOG_AGREEMENT_SUBMIT_TO_TLO = "29";
//    String ACTION_LOG_AGREEMENT_TERMINATED = "30";
//    String ACTION_LOG_AGREEMENT_TRANSFERRED = "31";
//    String ACTION_LOG_AGREEMENT_ABANDONED = "32";
//    String ACTION_LOG_AGREEMENT_REOPEN = "33";
//    String ACTION_LOG_AGREEMENT_SET_INPROGRESS = "34";
//    String ACTION_LOG_AGREEMENT_COMPLETE_REVIEW = "35";
//
//    //location type code
//    String LOCATION_STATUS_CODE_ASSIGNED = "1";
//    String lOCATION_STATUS_CODE_INPROGRESS = "2";
//    String LOCATION_STATUS_CODE_COMPLETED = "3";
//
//    //Agreement Review Types
//    String SUBMIT_TO_3RD_PARTY = "1";
//    String SUBMIT_TO_LEGAL = "2";
//    String SUBMIT_TO_HOD = "3";
//    String PUT_ON_HOLD = "4";
//    String SUBMIT_TO_OTHER_PARTY = "5";
//    String SUBMIT_TO_OGC = "6";
//    String SUBMIT_TO_RAS = "7";
//    String SUBMIT_TO_TLO = "8";
//    String SET_INPROGREES = "9";
//    String COMPLETE_REVIEW = "10";
//
//    String AGREEMENT_SUMMARY_LETTER_TEMPLATE_TYPE_CODE = "500";
//
//    Integer LOCATION_ASSIGN_NOTIFICATION_CODE = 711;
//    Integer LOCATION_COMPLETE_NOTIFICATION_CODE = 712;
//    Integer CREATE_AGREEMENT_NOTIFICATION_CODE = 713;
//    Integer SUBMIT_AGREEMENT_NOTIFICATION_CODE = 714;
//    Integer GENERATE_AGREEMENT_NOTIFICATION_CODE = 715;
//    Integer REGENERATE_AGREEMENT_NOTIFICATION_CODE = 716;
//    Integer REPLACE_AGREEMENT_NOTIFICATION_CODE = 717;
//    Integer RETURN_TO_PI_AGREEMENT_NOTIFICATION_CODE = 1414;
    String ADDTO_ADDRESSBOOK_ACTIVE_BY_DEFAULT = "ADDTO_ADDRESSBOOK_ACTIVE_BY_DEFAULT";
//    //Award Budget Integration
//    String AWARD_BUDGET_API = "BUDGET_API";
//    String BUDGET_API_AUTHORIZATION = "AUTHORIZATION";
//    String YEAR_TO_FETCH = "YEAR_TO_FETCH";
//
//    String ENABLE_CLOSED_GRANTCALL_LINKING_IN_DOCUMENT = "ENABLE_CLOSED_GRANTCALL_LINKING_IN_DOCUMENT";
//
//    // parameter used to enable socket and lock
//    String ENABLE_SOCKET = "ENABLE_SOCKET";
//    String ENABLE_LOCK = "ENABLE_LOCK";
//    
//    String INBOX_PROPOSAL_PERSON_CERTIFICATION_REQUIRED  = "133";
//    
//	// Sap Integration Profit Center
//	String OAUTH_API = "OAUTH_API";
//	String SAP_INTEGRATION_API_BASE = "SAP_INTEGRATION_API_BASE";
//	String SAP_INTEGRATION_EMAIL_RECIPIENT = "SAP_INTEGRATION_EMAIL_RECIPIENT";
//	String SAP_ACCESS_TOKEN_USERNAME = "SAP_ACCESS_TOKEN_USERNAME";
//	String SAP_ACCESS_TOKEN_PASSWORD = "SAP_ACCESS_TOKEN_PASSWORD";
//	
//	String MANPOWER_VIEW_BASE_SALARY_RIGHT_AUDIT_REPORT = "MANPOWER_VIEW_BASE_SALARY_RIGHT_AUDIT_REPORT";
//	Integer MANPOWER_VIEW_BASE_SALARY_RIGHT_AUDIT_REPORT_EMAIL_ROLE = 30;
//
//	Integer SERVICE_REQUEST_PRIORITY_NORMAL = 2;
//	String SR_ADMIN_GROUP_RIGHT = "VIEW_ASSIGMENT_GROUP_SERVICE_REQUEST";
//	String ENABLE_ORGANIZATION_LOCATION = "ENABLE_ORGANIZATION_LOCATION";
//	
//	String PROFIT_CENTER_API = "CPI_Profit_Center_API?IM_UNLOCKED=X&IM_RESEARCH=X";
//	String COST_CENTER_API = "CPI_Cost_Center_API?IM_UNLOCKED=X&IM_RESEARCH=X";
//	String GRANT_CODE_API = "CPI_Grant_API/";
//	String FUND_CENTER_API = "CPI_Fund_Center_API?IM_RESEARCH=X";
//	
//    String NO_OF_DAYS_INTERNAL_DEADLINE_DATE = "NO_OF_DAYS_INTERNAL_DEADLINE_DATE";
//    String ENABLE_COST_SHARE_STATUS = "ENABLE_COST_SHARE_STATUS";
//
    String JAVA_ERROR = "ERR";
    String DB_PROC_ERROR = "ERRP";
    String DB_FN_ERROR = "ERRF";

	//MetaRule Condition
    String NEXT_NODE = "N";
    String NODE_IF_TRUE = "T";
    String NODE_IF_FALSE = "F";
//
//    Integer AGREEMENT_BYPASS_NOTIFICATION_CODE = 753;
//    Integer NOTIFICATION_AGREEMENT_REJECTED = 755;
//    Integer AGREEMENT_FINAL_APPROVAL_NOTIFICATION_CODE = 756;
//
//
//    String ENABLE_AB_FIELDS_FOR_SAP = "ENABLE_AB_FIELDS_FOR_SAP";
//
//	Integer SERVICE_REQUEST_BYPASS_NOTIFICATION_CODE = 757;
//
	String HASH_ALGORITHM_SHA = "SHA-256";
	String REVIEWER = "1";
//
//	String EXTERNAL_REVIEW_TYPE_CODE_MAIN_PROPOSAL = "1";
//	String EXTERNAL_REVIEW_TYPE_CODE_PRE_PROPOSAL = "2";
//
//	Integer EXT_REVIEW_STATUS_CODE_ACTIVE = 3;
//
//	String EXT_REV_REVIEWER_FLOW_STATUS_CODE_PENDING = "1";
//
//	Integer EXT_REVIEW_ACTION_TYPE_CREATED = 1;
//
//	Integer EXT_REV_REVIEWER_STATUS_CODE_FINALIZED = 3;
//	Integer EXT_REV_REVIEWER_STATUS_CODE_RESERVED = 5;
//
//	String EXT_REVIEWERS_STATUS_CODE_ACTIVE = "1";
//    String EXT_REVIEWERS_STATUS_CODE_INACTIVE = "2";
//    String EXT_REVIEWERS_STATUS_CODE_ONHOLD = "3";
	Integer EXTERNAL_REVIEWER_MAIL = 752;
	Integer EXTERNAL_REVIEWER_MODULE_CODE = 22;
	String EXTERNAL_REVIEWER_SUB_MODULE_CODE = "913";
//
//	String SUPPORT_ADMINISTRATION = "SUPPORT_ADMINISTRATION";
//	
//	String MANPOWER_INTERFACE_STATUS_OPEN = "1";
//    String MANPOWER_INTERFACE_STATUS_FILLED = "2";
	
}
