package com.polus.core.utils;

public interface DashBoardQueries {
	
	String APPROVAL_INPROGRESS_PROPOSAL = "SELECT 'Approval In Progress Proposals' AS APPROVAL_INPROGRESS_PROPOSALS, COUNT(T1.PROPOSAL_ID) AS COUNT,SUM(T2.TOTAL_COST) AS TOTAL_AMOUNT FROM EPS_PROPOSAL T1 \r\n" + 
			"LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_FINAL_BUDGET = 'Y' WHERE T1.STATUS_CODE = 2 \r\n" + 
			"AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :personId UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL\r\n" + 
			"WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN  ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :personId) \r\n" + 
			"UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = :personId  UNION\r\n" + 
			"SELECT S1.MODULE_ITEM_ID FROM WORKFLOW S1 INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID WHERE S1.IS_WORKFLOW_ACTIVE = 'Y'\r\n" + 
			"AND S2.APPROVER_PERSON_ID = :personId AND S1.MODULE_CODE = 3)	";
	
	String APPROVAL_INPROGRESS_PROPOSAL_LIST = " SELECT T1.PROPOSAL_ID, T1.TITLE, T5.SPONSOR_NAME, ifnull(T2.TOTAL_COST,0.00) as TOTAL_COST, T4.FULL_NAME AS PI, T6.UNIT_NAME, T1.SPONSOR_DEADLINE_DATE  \r\n" + 
			"FROM EPS_PROPOSAL T1 LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_FINAL_BUDGET = 'Y' 			\r\n" + 
			"LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG ='Y' \r\n" + 
			"LEFT OUTER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE \r\n" + 
			"LEFT OUTER JOIN UNIT T6 ON  T1.HOME_UNIT_NUMBER= T6.UNIT_NUMBER\r\n" + 
			"WHERE T1.STATUS_CODE = 2  \r\n" + 
			"AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :personId UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL \r\n" + 
			"WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :personId)  \r\n" + 
			"UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = :personId  UNION \r\n" + 
			"SELECT S1.MODULE_ITEM_ID FROM WORKFLOW S1 INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID WHERE S1.IS_WORKFLOW_ACTIVE = 'Y'\r\n" + 
			"AND S2.APPROVER_PERSON_ID = :personId AND S1.MODULE_CODE = 3)";
	
	String APPROVAL_INPROGRESS_PROPOSAL_WITH_UNIT = "SELECT 'Approval In Progress Proposals' AS APPROVAL_INPROGRESS_PROPOSALS, COUNT(T1.PROPOSAL_ID) AS COUNT,SUM(T2.TOTAL_COST) AS TOTAL_AMOUNT FROM EPS_PROPOSAL T1 \r\n" + 
			"LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_FINAL_BUDGET = 'Y' WHERE T1.STATUS_CODE = 2 AND T1.HOME_UNIT_NUMBER = :unitNumber ";
	
	String APPROVAL_INPROGRESS_PROPOSAL_LIST_WITH_UNIT = "SELECT T1.PROPOSAL_ID, T1.TITLE, T5.SPONSOR_NAME, ifnull(T2.TOTAL_COST,0.00) as TOTAL_COST, T4.FULL_NAME AS PI, T6.UNIT_NAME, T1.SPONSOR_DEADLINE_DATE \r\n" + 
			"FROM EPS_PROPOSAL T1 LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_FINAL_BUDGET = 'Y'\r\n" + 
			"LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID  AND T4.PI_FLAG ='Y' \r\n" + 
			"INNER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE INNER JOIN UNIT T6 ON  T1.HOME_UNIT_NUMBER= T6.UNIT_NUMBER \r\n"+ 
			"WHERE T1.STATUS_CODE = 2 AND T1.HOME_UNIT_NUMBER = :unitNumber ";

	
	String INPROGRESS_PROPOSAL = "SELECT 'In Progress Proposals' AS INPROGRESS_PROPOSALS, COUNT(T1.PROPOSAL_ID) AS COUNT,SUM(T2.TOTAL_COST) AS TOTAL_AMOUNT FROM EPS_PROPOSAL T1 \r\n" + 
			"LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_LATEST_VERSION  = 'Y'  WHERE T1.STATUS_CODE = 1 AND T1.PROPOSAL_ID IN (\r\n" + 
			"SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :personId UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL WHERE HOME_UNIT_NUMBER IN (\r\n" + 
			"SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :personId) UNION\r\n" + 
			"SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = :personId)";
	
	String INPROGRESS_PROPOSAL_WITH_UNIT = "SELECT 'In Progress Proposals' AS INPROGRESS_PROPOSALS, COUNT(T1.PROPOSAL_ID) AS COUNT,SUM(T2.TOTAL_COST) AS TOTAL_AMOUNT \r\n" + 
			"FROM EPS_PROPOSAL T1 LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_LATEST_VERSION  = 'Y' \r\n" + 
			"WHERE T1.STATUS_CODE = 1 AND T1.HOME_UNIT_NUMBER = :unitNumber";
	
	String INPROGRESS_PROPOSAL_LIST = "SELECT T1.PROPOSAL_ID, T1.TITLE, T5.SPONSOR_NAME, ifnull(T2.TOTAL_COST,0.00) as TOTAL_COST, T4.FULL_NAME AS PI, T6.UNIT_NAME, T1.SPONSOR_DEADLINE_DATE \r\n" + 
			"FROM EPS_PROPOSAL T1 LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_LATEST_VERSION  = 'Y' \r\n" + 
			"LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG ='Y' \r\n" + 
			"LEFT OUTER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE INNER JOIN UNIT T6 ON  T1.HOME_UNIT_NUMBER= T6.UNIT_NUMBER \r\n" +  
			"WHERE T1.STATUS_CODE = 1 AND T1.PROPOSAL_ID IN (\r\n" + 
			"SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :personId UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL WHERE HOME_UNIT_NUMBER IN (\r\n" + 
			"SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :personId) UNION\r\n" + 
			"SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = :personId)";
	
	String INPROGRESS_PROPOSAL_LIST_WITH_UNIT = "SELECT T1.PROPOSAL_ID, T1.TITLE, T5.SPONSOR_NAME, ifnull(T2.TOTAL_COST,0.00) as TOTAL_COST, T4.FULL_NAME AS PI, T6.UNIT_NAME, T1.SPONSOR_DEADLINE_DATE \r\n" + 
			"FROM EPS_PROPOSAL T1 LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_LATEST_VERSION  = 'Y' \r\n" + 
			"LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG ='Y' \r\n" + 
			"LEFT OUTER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE INNER JOIN UNIT T6 ON  T1.HOME_UNIT_NUMBER= T6.UNIT_NUMBER \r\n" + 
			"WHERE T1.STATUS_CODE = 1 AND T1.HOME_UNIT_NUMBER = :unitNumber";
	
	String SUMMARY_INPROGRESS_PIE_CHART_WITH_UNIT = "SELECT T2.SPONSOR_TYPE_CODE, T3.DESCRIPTION AS SPONSOR_TYPE, COUNT(1) FROM EPS_PROPOSAL T1 \r\n" + 
			"INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE=T2.SPONSOR_CODE INNER JOIN SPONSOR_TYPE T3 ON T2.SPONSOR_TYPE_CODE=T3.SPONSOR_TYPE_CODE \r\n" + 
			"WHERE T1.HOME_UNIT_NUMBER = :unitNumber GROUP BY T2.SPONSOR_TYPE_CODE, T3.DESCRIPTION";
	
	String SUMMARY_INPROGRESS_PIE_CHART = "SELECT T2.SPONSOR_TYPE_CODE, T3.DESCRIPTION AS SPONSOR_TYPE,COUNT(1) FROM EPS_PROPOSAL T1 INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE=T2.SPONSOR_CODE \r\n" + 
			"INNER JOIN SPONSOR_TYPE T3 ON T2.SPONSOR_TYPE_CODE=T3.SPONSOR_TYPE_CODE WHERE T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL\r\n" + 
			"WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :personId) 	\r\n" + 
			"UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :personId UNION\r\n" + 
			"SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = :personId UNION SELECT S1.MODULE_ITEM_ID FROM WORKFLOW S1 \r\n" + 
			"INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID WHERE S1.IS_WORKFLOW_ACTIVE = 'Y' AND S2.APPROVER_PERSON_ID = :personId							\r\n" + 
			"AND S1.MODULE_CODE = 3) GROUP BY T2.SPONSOR_TYPE_CODE, T3.DESCRIPTION";
	
	String SUMMARY_INPROGRESS_DONET_WITH_UNIT ="SELECT T1.SPONSOR_CODE,T2.SPONSOR_NAME AS SPONSOR,COUNT(1) AS COUNT FROM EPS_PROPOSAL T1 INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE=T2.SPONSOR_CODE \r\n" + 
			"WHERE T1.STATUS_CODE = 1 AND T1.HOME_UNIT_NUMBER = :unitNumber GROUP BY T1.SPONSOR_CODE,T2.SPONSOR_NAME";
	
	String SUMMARY_INPROGRESS_DONET = "SELECT T1.SPONSOR_CODE,T2.SPONSOR_NAME AS SPONSOR,COUNT(1) AS COUNT FROM EPS_PROPOSAL T1 INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE=T2.SPONSOR_CODE WHERE T1.STATUS_CODE = 1 \r\n" + 
			"AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL')\r\n" + 
			"AND PERSON_ID = :personId) UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :personId UNION\r\n" + 
			"SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = :personId UNION SELECT S1.MODULE_ITEM_ID FROM WORKFLOW S1 INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID\r\n" + 
			"WHERE S1.IS_WORKFLOW_ACTIVE = 'Y' AND S2.APPROVER_PERSON_ID = :personId	AND S1.MODULE_CODE = 3) GROUP BY T1.SPONSOR_CODE,T2.SPONSOR_NAME";

	String SUMMARY_AWARD_PIE_CHART_WITH_UNIT = "SELECT T2.SPONSOR_TYPE_CODE, T3.DESCRIPTION AS SPONSOR_TYPE, COUNT(1) FROM AWARD T1 INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE=T2.SPONSOR_CODE \r\n" + 
			"INNER JOIN SPONSOR_TYPE T3 ON T2.SPONSOR_TYPE_CODE=T3.SPONSOR_TYPE_CODE WHERE T1.AWARD_SEQUENCE_STATUS = 'ACTIVE' AND T1.LEAD_UNIT_NUMBER = :unitNumber group by T2.SPONSOR_TYPE_CODE,T3.DESCRIPTION";
	
	String SUMMARY_AWARD_PIE_CHART = "SELECT T2.SPONSOR_TYPE_CODE, T3.DESCRIPTION AS SPONSOR_TYPE, COUNT(1) FROM AWARD T1 INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE=T2.SPONSOR_CODE \r\n" + 
			"INNER JOIN SPONSOR_TYPE T3 ON T2.SPONSOR_TYPE_CODE=T3.SPONSOR_TYPE_CODE WHERE T1.AWARD_SEQUENCE_STATUS = 'ACTIVE' AND T1.AWARD_NUMBER IN (\r\n" + 
			"SELECT AWARD_NUMBER FROM AWARD WHERE LEAD_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_AWARD','VIEW_AWARD')\r\n" + 
			"AND PERSON_ID = :personId) UNION SELECT AWARD_NUMBER FROM AWARD_PERSONS WHERE PERSON_ID = :personId AND PERSON_ROLE_ID IN ('1','2','3')) \r\n" + 
			"group by T2.SPONSOR_TYPE_CODE,T3.DESCRIPTION";
	
	String SUMMARY_AWARD_DONET_WITH_UNIT = "SELECT T1.SPONSOR_CODE,T1.SPONSOR_NAME AS SPONSOR,COUNT(1) AS COUNT FROM PROPOSAL T1 WHERE T1.STATUS_CODE = 2 AND T1.HOME_UNIT_NUMBER = :unitNumber GROUP BY T1.SPONSOR_CODE,T1.SPONSOR_NAME";
	
	String SUMMARY_AWARD_DONET = "SELECT T1.SPONSOR_CODE,T1.SPONSOR_NAME AS SPONSOR,COUNT(1) AS COUNT FROM PROPOSAL T1 WHERE T1.STATUS_CODE = 2 \r\n" + 
			"AND T1.PROPOSAL_NUMBER IN (SELECT PROPOSAL_NUMBER FROM PROPOSAL WHERE T1.HOME_UNIT_NUMBER IN \r\n" + 
			"(SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :personId) UNION\r\n" + 
			"SELECT PROPOSAL_ID FROM PROPOSAL_PERSONS WHERE PERSON_ID = :personId) GROUP BY T1.SPONSOR_CODE,T1.SPONSOR_NAME";
//	------------------------------------------------------Expand details from chart -------------------------------------------------------------------
	String AWARD_BY_SPONSOR_WITH_UNIT = "SELECT T1.SEQUENCE_NUMBER, T1.AWARD_ID, T1.AWARD_NUMBER, T1.ACCOUNT_NUMBER, T1.TITLE, T2.SPONSOR_NAME, T3.FULL_NAME AS PI FROM AWARD T1 \r\n" + 
			"INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE LEFT OUTER JOIN AWARD_PERSONS T3 ON T1.AWARD_ID = T3.AWARD_ID AND T3.CONTACT_ROLE_CODE = 'PI' \r\n" + 
			"WHERE T2.SPONSOR_TYPE_CODE = :sponsorCode AND T1.AWARD_SEQUENCE_STATUS = 'ACTIVE' AND T1.LEAD_UNIT_NUMBER = :unitNumber";
	
	String AWARD_BY_SPONSOR = "SELECT T1.SEQUENCE_NUMBER, T1.AWARD_ID,T1.AWARD_NUMBER, T1.ACCOUNT_NUMBER, T1.TITLE, T2.SPONSOR_NAME, T3.FULL_NAME AS PI FROM AWARD T1 \r\n" + 
			"INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE LEFT OUTER JOIN AWARD_PERSONS T3 ON T1.AWARD_ID = T3.AWARD_ID AND T3.PI_FLAG ='Y' \r\n" + 
			"WHERE T2.SPONSOR_TYPE_CODE = :sponsorCode AND T1.AWARD_SEQUENCE_STATUS = 'ACTIVE' AND T1.AWARD_NUMBER IN (SELECT AWARD_NUMBER FROM AWARD WHERE LEAD_UNIT_NUMBER IN (\r\n" + 
			"SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_AWARD','VIEW_AWARD') AND PERSON_ID = :personId) UNION SELECT AWARD_NUMBER FROM AWARD_PERSONS WHERE PERSON_ID = :personId AND PERSON_ROLE_ID IN ('1','2','3'))";
	
	String PROPOSAL_BY_SPONSOR_WITH_UNIT = "\r\n" + 
			"SELECT T1.PROPOSAL_ID, T1.TITLE, T2.SPONSOR_NAME, T4.DESCRIPTION AS PROPOSAL_TYPE, T3.FULL_NAME AS PI, T1.SUBMISSION_DATE FROM EPS_PROPOSAL T1 \r\n" + 
			"INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T3 ON T1.PROPOSAL_ID = T3.PROPOSAL_ID  AND  T3.PI_FLAG ='Y' \r\n" + 
			"INNER JOIN EPS_PROPOSAL_TYPE T4 ON T1.TYPE_CODE = T4.TYPE_CODE WHERE T2.SPONSOR_TYPE_CODE = :sponsorCode AND AND T1.LEAD_UNIT_NUMBER = :unitNumber";
	
	String PROPOSAL_BY_SPONSOR ="\r\n" + 
			"SELECT T1.PROPOSAL_ID, T1.TITLE, T2.SPONSOR_NAME, T4.DESCRIPTION AS PROPOSAL_TYPE, T3.FULL_NAME AS PI, T1.SUBMISSION_DATE FROM EPS_PROPOSAL T1 \r\n" + 
			"INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T3 ON T1.PROPOSAL_ID = T3.PROPOSAL_ID AND T3.PI_FLAG ='Y' \r\n" + 
			"INNER JOIN EPS_PROPOSAL_TYPE T4 ON T1.TYPE_CODE = T4.TYPE_CODE WHERE T2.SPONSOR_TYPE_CODE = :sponsorCode AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL\r\n" + 
			"WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL')AND PERSON_ID = :personId ) UNION\r\n" + 
			"SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :personId )";
	
	String PROPOSAL_DONUT_WITH_SPONSOR_AND_UNIT = "SELECT T1.PROPOSAL_ID, T1.TITLE, T4.FULL_NAME AS PI, T1.TYPE_CODE, T5.DESCRIPTION AS PROPOSAL_TYPE, ifnull(T6.TOTAL_COST,'0.00') AS BUDGET, T1.SUBMISSION_DATE \r\n" + 
			"FROM EPS_PROPOSAL T1 LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG ='Y' INNER JOIN EPS_PROPOSAL_TYPE T5 ON T1.TYPE_CODE=T5.TYPE_CODE \r\n" + 
			"LEFT OUTER JOIN BUDGET_HEADER T6 ON T1.BUDGET_HEADER_ID = T6.BUDGET_HEADER_ID WHERE T1.STATUS_CODE = 1 AND T1.SPONSOR_CODE = :sponsorCode AND AND T1.HOME_UNIT_NUMBER = :unitNumber ";
	
	String PROPOSAL_DONUT_WITH_SPONSOR ="\r\n" + 
			"SELECT T1.PROPOSAL_ID, T1.TITLE, T4.FULL_NAME AS PI, T1.TYPE_CODE, T5.DESCRIPTION AS PROPOSAL_TYPE, ifnull(T6.TOTAL_COST,'0.00') AS BUDGET, T1.SUBMISSION_DATE FROM EPS_PROPOSAL T1 \r\n" + 
			"LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND  T4.PI_FLAG ='Y' INNER JOIN EPS_PROPOSAL_TYPE T5 ON T1.TYPE_CODE=T5.TYPE_CODE \r\n" + 
			"LEFT OUTER JOIN BUDGET_HEADER T6 ON T1.BUDGET_HEADER_ID = T6.BUDGET_HEADER_ID WHERE T1.STATUS_CODE = 1 AND T1.SPONSOR_CODE = :sponsorCode  \r\n" + 
			"AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL')\r\n" + 
			"AND PERSON_ID = :personId)UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :personId UNION\r\n" + 
			"SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = :personId UNION SELECT S1.MODULE_ITEM_ID FROM WORKFLOW S1 INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID\r\n" + 
			"WHERE S1.IS_WORKFLOW_ACTIVE = 'Y' AND S2.APPROVER_PERSON_ID = :personId	AND S1.MODULE_CODE = 3)	";
	
	String AWARD_DONUT_WITH_SPONSOR_AND_UNIT = "SELECT T1.PROPOSAL_NUMBER, T1.TITLE, T4.FULL_NAME AS PI, T1.ACTIVITY_TYPE_CODE, T5.DESCRIPTION AS ACTIVITY_TYPE, T1.TYPE_CODE as PROPOSAL_TYPE_CODE,T6.DESCRIPTION AS PROPOSAL_TYPE, \r\n" + 
			"T1.SPONSOR_CODE, T1.PROPOSAL_ID FROM PROPOSAL T1 INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE LEFT OUTER JOIN PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PROP_PERSON_ROLE_ID = 3 \r\n" + 
			"INNER JOIN ACTIVITY_TYPE T5 ON T1.ACTIVITY_TYPE_CODE = T5.ACTIVITY_TYPE_CODE INNER JOIN PROPOSAL_TYPE T6 ON T1.TYPE_CODE = T6.TYPE_CODE\r\n" + 
			"WHERE  T1.STATUS_CODE = 2 AND T1.SPONSOR_CODE = :sponsorCode AND T1.HOME_UNIT_NUMBER = :unitNumber";
	
	String AWARD_DONUT_WITH_SPONSOR = "SELECT T1.PROPOSAL_NUMBER, T1.TITLE, T4.FULL_NAME AS PI, T1.ACTIVITY_TYPE_CODE, T5.DESCRIPTION AS ACTIVITY_TYPE, T1.TYPE_CODE as PROPOSAL_TYPE_CODE,T6.DESCRIPTION AS PROPOSAL_TYPE, \r\n" + 
			"T1.SPONSOR_CODE, T1.PROPOSAL_ID FROM PROPOSAL T1 INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE LEFT OUTER JOIN PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PROP_PERSON_ROLE_ID = 3 \r\n" + 
			"INNER JOIN ACTIVITY_TYPE T5 ON T1.ACTIVITY_TYPE_CODE = T5.ACTIVITY_TYPE_CODE INNER JOIN PROPOSAL_TYPE T6 ON T1.TYPE_CODE = T6.TYPE_CODE WHERE  T1.STATUS_CODE = 2 \r\n" + 
			"AND T1.SPONSOR_CODE = :sponsorCode AND T1.PROPOSAL_NUMBER IN (SELECT PROPOSAL_NUMBER FROM PROPOSAL WHERE HOME_UNIT_NUMBER IN \r\n" + 
			"(SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :personId) UNION SELECT PROPOSAL_ID FROM \r\n" + 
			"PROPOSAL_PERSONS WHERE PERSON_ID = :personId)";
	
	String EXPENDITURE_VOLUME = "SELECT DATE_FORMAT(T3.START_DATE, '%Y') AS BUDGET_PERIOD, SUM(T3.TOTAL_DIRECT_COST) AS DIRECT_COST, SUM(T3.TOTAL_INDIRECT_COST) AS FA \r\n" + 
			"FROM EPS_PROPOSAL T1 INNER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID   AND T2.IS_LATEST_VERSION  = 'Y' \r\n" + 
			"INNER JOIN BUDGET_PERIOD T3 ON T2.BUDGET_HEADER_ID = T3.BUDGET_HEADER_ID WHERE T1.PROPOSAL_ID IN(\r\n" + 
			"SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :personId UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL\r\n" + 
			"WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :personId) \r\n" + 
			"UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = :personId)GROUP BY YEAR(T3.START_DATE) ORDER BY YEAR(T3.START_DATE)"; 
	
	String EXPENDITURE_VOLUME_WITH_UNIT = "SELECT DATE_FORMAT(T3.START_DATE, '%Y') AS BUDGET_PERIOD, SUM(T3.TOTAL_DIRECT_COST) AS DIRECT_COST, SUM(T3.TOTAL_INDIRECT_COST) AS FA \r\n" + 
			"FROM EPS_PROPOSAL T1 \r\n" + 
			"INNER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID   AND T2.IS_LATEST_VERSION  = 'Y' \r\n" + 
			"INNER JOIN BUDGET_PERIOD T3 ON T2.BUDGET_HEADER_ID = T3.BUDGET_HEADER_ID \r\n" + 
			"WHERE T1.HOME_UNIT_NUMBER = :unitNumber\r\n" + 
			"GROUP BY YEAR(T3.START_DATE) ORDER BY YEAR(T3.START_DATE)"	;
	
	String EXPENDITURE_VOLUME_ORACLE = "SELECT TO_CHAR(T3.START_DATE, '%Y') AS BUDGET_PERIOD, SUM(T3.TOTAL_DIRECT_COST) AS DIRECT_COST, SUM(T3.TOTAL_INDIRECT_COST) AS FA \r\n" + 
			"FROM EPS_PROPOSAL T1 INNER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID   AND T2.IS_LATEST_VERSION  = 'Y' \r\n" + 
			"INNER JOIN BUDGET_PERIOD T3 ON T2.BUDGET_HEADER_ID = T3.BUDGET_HEADER_ID WHERE T1.PROPOSAL_ID IN(\r\n" + 
			"SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :personId UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL\r\n" + 
			"WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :personId) \r\n" + 
			"UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = :personId)GROUP BY YEAR(T3.START_DATE) ORDER BY YEAR(T3.START_DATE)"; 
	
	String EXPENDITURE_VOLUME_WITH_UNIT_ORACLE = "SELECT TO_CHAR(T3.START_DATE, '%Y') AS BUDGET_PERIOD, SUM(T3.TOTAL_DIRECT_COST) AS DIRECT_COST, SUM(T3.TOTAL_INDIRECT_COST) AS FA \r\n" + 
			"FROM EPS_PROPOSAL T1 \r\n" + 
			"INNER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID   AND T2.IS_LATEST_VERSION  = 'Y' \r\n" + 
			"INNER JOIN BUDGET_PERIOD T3 ON T2.BUDGET_HEADER_ID = T3.BUDGET_HEADER_ID \r\n" + 
			"WHERE T1.HOME_UNIT_NUMBER = :unitNumber\r\n" + 
			"GROUP BY YEAR(T3.START_DATE) ORDER BY YEAR(T3.START_DATE)"	;
//	----------------------------------------------------For Inprogress proposal list-------------------------------------------------------------------
	
	String WORKFLOW_APPROVAL_WAITING_PERSONS = "SELECT S1.MODULE_ITEM_ID \n" + 
			"							FROM WORKFLOW S1 \n" + 
			"							INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID\n" + 
			"							WHERE S1.IS_WORKFLOW_ACTIVE = 'Y'\n" + 
			"							AND S2.APPROVER_PERSON_ID = :reviewer_person_id\n" + 
			"							AND S2.APPROVAL_STATUS = :approval_status_code\n" + 
			"							AND S1.MODULE_CODE = :module_code";
	
	String PROPOSAL_PRE_REVIEW_LIST ="SELECT DISTINCT MODULE_ITEM_KEY FROM PRE_REVIEW \n" + 
			"							WHERE REVIEWER_PERSON_ID = :person_id\n" + 
			"							AND PRE_REVIEW_STATUS_CODE = :pre_review_status_code\n" + 
			"							AND PRE_REVIEW_TYPE_CODE = :pre_review_type_code\n" +
			"							AND MODULE_ITEM_CODE = :module_code";
	
//	----------------------------------------------------For My proposal proposal list-------------------------------------------------------------------

	String GET_PROPOSAL_FOR_PERSON = "SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :person_id";
	
	String GET_PROPOSAL_FOR_USER_ROLE = "SELECT PROPOSAL_ID FROM EPS_PROPOSAL \r\n" + 
			"WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL')\r\n" + 
			"AND PERSON_ID = :person_id)";
	
	String GET_PROPOSAL_FOR_DERIVED_ROLE = "SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = :person_id";
	
	String GET_PROPOSAL_FORM_MY_WORKFLOW = "SELECT S1.MODULE_ITEM_ID FROM WORKFLOW S1 INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID WHERE S1.IS_WORKFLOW_ACTIVE = 'Y' AND S2.APPROVER_PERSON_ID = :person_id AND S1.MODULE_CODE = :module_code AND APPROVAL_STATUS = 'W'";
	
	String GET_MY_PRE_REVIEW_PROPOSAL = "SELECT DISTINCT MODULE_ITEM_KEY FROM PRE_REVIEW  WHERE REQUESTOR_PERSON_ID = :person_id AND MODULE_ITEM_CODE = :module_code";

	String GET_PROPOSAL_FOR_CREATE_USER ="SELECT PROPOSAL_ID FROM EPS_PROPOSAL WHERE CREATE_USER = (SELECT USER_NAME FROM PERSON WHERE PERSON_ID = :person_id)";

	String GET_PROPOSAL_FOR_UNIT_ADMIN = "SELECT PROPOSAL_ID FROM EPS_PROPOSAL WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = :person_id AND UNIT_ADMINISTRATOR_TYPE_CODE = 3)";

	String LIST_OF_REVIEW_COMPLETED_PROPOSALS = "SELECT PROPOSAL_ID FROM EPS_PROPOSAL WHERE STATUS_CODE IN(28,31,18,21,11) AND HOME_UNIT_NUMBER IN \r\n" + 
			"((SELECT DISTINCT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :person_id) \r\n" + 
			"UNION \r\n" + 
			"(SELECT DISTINCT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = :person_id AND UNIT_ADMINISTRATOR_TYPE_CODE = 3))";

	String LIST_OF_REVIEW_INPROGRESS_PROPOSALS = "SELECT PROPOSAL_ID FROM EPS_PROPOSAL WHERE STATUS_CODE NOT IN(1,3,4,5,6,7,8,9,10,11,12,20,22,24,29,30) AND HOME_UNIT_NUMBER IN  (\r\n" + 
			"				(SELECT DISTINCT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :person_id)\r\n" + 
			"			UNION\r\n" + 
			"				(SELECT DISTINCT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = :person_id AND UNIT_ADMINISTRATOR_TYPE_CODE = 3))";

//  ----------------------------------------------------For Downloads----------------------------------------------------------------
	String DOWNLOAD_REVIEW_PENDING_PROPOSAL = "SELECT \r\n" + 
			"T1.PROPOSAL_ID, \r\n" + 
			"T1.TITLE, \r\n" + 
			"T5.SPONSOR_NAME, \r\n" + 
			"T2.TOTAL_COST, \r\n" + 
			"T4.FULL_NAME AS PI, \r\n" + 
			"T1.SUBMISSION_DATE FROM EPS_PROPOSAL T1 \r\n" + 
			"LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.BUDGET_HEADER_ID=T2.BUDGET_HEADER_ID \r\n" + 
			"LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND  T4.PI_FLAG ='Y' \r\n" + 
			"INNER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE \r\n" + 
			"INNER JOIN UNIT T6 ON T1.HOME_UNIT_NUMBER= T6.UNIT_NUMBER WHERE T1.STATUS_CODE=1 AND (\r\n" + 
			"T1.HOME_UNIT_NUMBER IN( SELECT DISTINCT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME ='VIEW_PROPOSAL' and PERSON_ID = :person_id) \r\n" + 
			"OR T1.PROPOSAL_ID IN ( "+ WORKFLOW_APPROVAL_WAITING_PERSONS+
			"								UNION\r\n" + 
			"								"+PROPOSAL_PRE_REVIEW_LIST+"))";

//	------------------------------------------------Dash board data----------------------------------------------------------------
	String DASHBOARD_DATA_FOR_AWARD = 
			"		SELECT \r\n" + 
			"			T1.AWARD_ID AS DOCUMENT_NUMBER,\r\n" + 
			"			T1.AWARD_NUMBER AS AWARD_NUMBER,\r\n" + 
			"			T1.AWARD_ID AS AWARD_ID,\r\n" + 
			"			T1.TITLE AS TITLE,\r\n" + 
			"			T1.ACCOUNT_NUMBER AS ACCOUNT_NUMBER,\r\n" + 
			"			T1.SEQUENCE_NUMBER AS SEQUENCE_NUMBER,\r\n" + 
			"			T4.DESCRIPTION AS STATUS,\r\n" + 
			"			T2.SPONSOR_NAME AS SPONSOR,\r\n" + 
			"			T1.SPONSOR_CODE AS SPONSOR_CODE,\r\n" + 
			"			T5.UNIT_NUMBER AS UNIT_NUMBER,\r\n" + 
			"			T5.UNIT_NAME AS UNIT_NAME,\r\n" + 
			"			T3.FULL_NAME AS FULL_NAME,\r\n" + 
			"			T3.PERSON_ID AS PERSON_ID,\r\n" + 
			"			T1.UPDATE_TIMESTAMP AS UPDATE_TIMESTAMP,\r\n" + 
			"			T1.UPDATE_USER AS UPDATE_USER\r\n" + 
			"		FROM AWARD T1 \r\n" + 
			"		INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE \r\n" + 
			"		LEFT OUTER JOIN AWARD_PERSONS T3 ON T1.AWARD_ID = T3.AWARD_ID AND T3.CONTACT_ROLE_CODE = 'PI' \r\n" + 
			"		INNER JOIN AWARD_STATUS T4 ON T1.STATUS_CODE = T4.STATUS_CODE\r\n" + 
			"		LEFT JOIN UNIT T5 ON T1.LEAD_UNIT_NUMBER = T5.UNIT_NUMBER\r\n" + 
			"		WHERE T1.IS_LATEST = 'Y'\r\n" + 
			"		AND T1.AWARD_NUMBER IN (\r\n" + 
			"\r\n" + 
			"									SELECT AWARD_NUMBER FROM AWARD\r\n" + 
			"												WHERE LEAD_UNIT_NUMBER IN (\r\n" + 
			"																				SELECT UNIT_NUMBER\r\n" + 
			"																				FROM PERSON_ROLE_RT \r\n" + 
			"																				WHERE RIGHT_NAME IN ('MODIFY_AWARD','VIEW_AWARD')\r\n" + 
			"																				AND PERSON_ID = :personId\r\n" + 
			"																			) 	\r\n" + 
			"									UNION\r\n" + 
			"									\r\n" + 
			"									SELECT AWARD_NUMBER FROM AWARD_PERSONS WHERE PERSON_ID = :personId AND PERSON_ROLE_ID IN ('1','2','3')\r\n" + 
			"								)\r\n" + 
			"		 ORDER BY T1.UPDATE_TIMESTAMP DESC  \r\n";
			
// ----------------------------------------------------- To get the active award number----------------------------------------------------

	String GET_MY_AWARDS = "SELECT T1.AWARD_ID FROM AWARD T1 INNER JOIN AWARD_PERSONS T2 ON T1.AWARD_ID = T2.AWARD_ID WHERE T1.IS_LATEST = 'Y' AND STATUS_CODE NOT IN (2,4,5)\r\n" +
			"				AND T2.PERSON_ID = :person_id AND T2.PERSON_ROLE_ID IN ('1','2','3')";

	String GET_MY_DRAFT_AWARDS = "SELECT T1.AWARD_ID FROM AWARD T1 WHERE T1.IS_LATEST = 'Y' AND STATUS_CODE NOT IN (2,4,5)\r\n" +
			"				AND T1.CREATE_USER = :user_name";

	String GET_MY_PENDING_AWARDS = "SELECT T1.MODULE_ITEM_ID AS AWARD_ID FROM WORKFLOW T1\r\n" + 
								   "inner join WORKFLOW_DETAIL T2 ON T1.WORKFLOW_ID = T2.WORKFLOW_ID\r\n" + 
								   "INNER JOIN AWARD T3 ON T1.MODULE_ITEM_ID = T3.AWARD_ID \r\n" + 
								   "AND T3.IS_LATEST = 'Y'\r\n" + 
								   "WHERE T2.APPROVER_PERSON_ID = :person_id\r\n" + 
								   "AND T2.APPROVAL_STATUS = 'W'\r\n" + 
								   "AND T1.MODULE_CODE= 1\r\n" + 
								   "AND T1.IS_WORKFLOW_ACTIVE = 'Y' \r\n" +
								   "UNION SELECT MODULE_ITEM_KEY AS AWARD_ID FROM PRE_REVIEW \r\n"+
								   "WHERE REQUESTOR_PERSON_ID = :person_id \r\n"+
								   "AND PRE_REVIEW_STATUS_CODE = 1";
	
	String GET_ALL_AWARDS = "SELECT AWARD_ID FROM AWARD WHERE IS_LATEST = 'Y'";
//	------------------------------------------------------Role------------------------------------
	String ROLE_WITH_UNIT = "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER,T2.PRIMARY_TITLE,T2.DIRECTORY_TITLE\r\n" + 
			"			FROM PERSON_ROLES T1 \r\n" + 
			"			INNER JOIN PERSON T2 ON T1.PERSON_ID = T2.PERSON_ID\r\n" + 
			"			INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER \r\n" + 
			"           WHERE T1.UNIT_NUMBER = :unitNumber";

	String ROLE_WITH_ROLE = "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER,T2.PRIMARY_TITLE,T2.DIRECTORY_TITLE\r\n" + 
			"			FROM PERSON_ROLES T1 \r\n" + 
			"			INNER JOIN PERSON T2 ON T1.PERSON_ID = T2.PERSON_ID\r\n" + 
			"			INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER \r\n" + 
			"           WHERE T1.ROLE_ID = :roleId";

	String ROLE_WITH_UNIT_AND_ROLE = "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER,T2.PRIMARY_TITLE,T2.DIRECTORY_TITLE\r\n" + 
			"			FROM PERSON_ROLES T1 \r\n" + 
			"			INNER JOIN PERSON T2 ON T1.PERSON_ID = T2.PERSON_ID\r\n" + 
			"			INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER \r\n" + 
			"           WHERE T1.ROLE_ID = :roleId AND T1.UNIT_NUMBER = :unitNumber";

	String FETCH_ALL_ROLES= "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER,T2.PRIMARY_TITLE,T2.DIRECTORY_TITLE\r\n" + 
			"			FROM PERSON_ROLES T1 \r\n" + 
			"			INNER JOIN PERSON T2 ON T1.PERSON_ID = T2.PERSON_ID\r\n" + 
			"			INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER";
	
	String ROLES_OF_PERSON = "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER,T2.PRIMARY_TITLE,T2.DIRECTORY_TITLE\r\n" + 
			"FROM PERSON_ROLES T1 \r\n" + 
			"INNER JOIN PERSON T2 ON T1.PERSON_ID = T2.PERSON_ID\r\n" + 
			"INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER \r\n" + 
			"WHERE T1.PERSON_ID = :personId";

	String ROLE_WITH_UNIT_AND_PERSON = "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER,T2.PRIMARY_TITLE,T2.DIRECTORY_TITLE\r\n" + 
			"			FROM PERSON_ROLES T1 \r\n" + 
			"			INNER JOIN PERSON T2 ON T1.PERSON_ID = T2.PERSON_ID\r\n" + 
			"			INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER \r\n" + 
			"           WHERE T1.PERSON_ID = :personId AND T1.UNIT_NUMBER = :unitNumber GROUP BY T1.UNIT_NUMBER";

	String ROLE_WITH_UNIT_AND_PERSON_AND_ROLE = "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER,T2.PRIMARY_TITLE,T2.DIRECTORY_TITLE\r\n" + 
			"			FROM PERSON_ROLES T1 \r\n" + 
			"			INNER JOIN PERSON T2 ON T1.PERSON_ID = T2.PERSON_ID\r\n" + 
			"			INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER \r\n" + 
			"           WHERE T1.PERSON_ID = :personId AND T1.UNIT_NUMBER = :unitNumber AND T1.ROLE_ID = :roleId";

	String ROLE_WITH_ROLE_AND_PERSON = "SELECT DISTINCT T1.PERSON_ID,T2.FULL_NAME,T2.EMAIL_ADDRESS,T2.USER_NAME,T3.UNIT_NAME,T1.UNIT_NUMBER,T2.PRIMARY_TITLE,T2.DIRECTORY_TITLE\r\n" + 
			"			FROM PERSON_ROLES T1 \r\n" + 
			"			INNER JOIN PERSON T2 ON T1.PERSON_ID = T2.PERSON_ID\r\n" + 
			"			INNER JOIN UNIT T3 ON T1.UNIT_NUMBER = T3.UNIT_NUMBER \r\n" + 
			"           WHERE T1.PERSON_ID = :personId AND T1.ROLE_ID = :roleId ";

//	------------------------------------------------------Evaluation------------------------------------
		String PROPOSAL_EVALUATION_LIST ="SELECT DISTINCT PROPOSAL_ID FROM PROPOSAL_REVIEW \n" + 
				"							WHERE REVIEW_STATUS_CODE = :review_status_code"; 
		String LIST_OF_PROPOSALS ="SELECT DISTINCT PROPOSAL_ID FROM EPS_PROPOSAL \n" + 
				"							WHERE STATUS_CODE != :status_code AND STATUS_CODE != :awared_status"; 
		String LIST_OF_PROPOSALS_UNDER_EVALUVATION ="SELECT DISTINCT PROPOSAL_ID FROM PROPOSAL_REVIEW \n" + 
				"							WHERE REVIEW_STATUS_CODE = :status_code AND REVIEWER_PERSON_ID = :reviewer_person_id ";

//------------------------------------------------------------AWARDED_PROPOSAL_WITH_UNIT---------------------------------------------------------------------------------------------------
		String AWARDED_PROPOSAL_WITH_UNIT ="SELECT 'Submitted Proposals' AS AWARDED_PROPOSALS,\r\n" + 
				" COUNT(T1.PROPOSAL_ID) AS COUNT,\r\n" + 
				" SUM(T2.TOTAL_COST) AS TOTAL_AMOUNT \r\n" + 
				" FROM EPS_PROPOSAL T1\r\n" + 
				"LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_FINAL_BUDGET = 'Y' \r\n" + 
				"WHERE T1.STATUS_CODE = 11 AND T1.HOME_UNIT_NUMBER = :unitNumber";
//------------------------------------------------------------AWARDED_PROPOSAL_WITHOUT_UNIT----------------------------------------------------------------------------------------------------
		String AWARDED_PROPOSAL_WITHOUT_UNIT="SELECT 'Submitted Proposals' AS AWARDED_PROPOSALS, COUNT(T1.PROPOSAL_ID) AS COUNT,SUM(T2.TOTAL_COST) AS TOTAL_AMOUNT \r\n" + 
				"FROM EPS_PROPOSAL T1\r\n" + 
				"LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_FINAL_BUDGET = 'Y' WHERE T1.STATUS_CODE = 11\r\n" + 
				"AND T1.PROPOSAL_ID IN (                SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :personId \r\n" + 
				"									   UNION \r\n" + 
				"									   SELECT PROPOSAL_ID FROM EPS_PROPOSAL\r\n" + 
				"			                           WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :personId) \r\n" + 
				"									   UNION \r\n" + 
				"									   SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = :personId\r\n" + 
				"									   UNION\r\n" + 
				"									   SELECT PROPOSAL_ID FROM EPS_PROPOSAL\r\n" + 
				"			                           WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = :personId AND UNIT_ADMINISTRATOR_TYPE_CODE = 3)\r\n" + 
				"						)";
		
//-------------------------------------------------------------Detailed LIST - AWARDED_PROPOSAL_WITH_UNIT-------------------------------------------------------------------------------------------------------------
		String DETAILED_AWARDED_PROPOSAL_WITH_UNIT="SELECT T1.PROPOSAL_ID, T1.TITLE, T5.SPONSOR_NAME, T2.TOTAL_COST, T4.FULL_NAME AS PI, T6.UNIT_NAME, T1.SPONSOR_DEADLINE_DATE\r\n" + 
				"			FROM EPS_PROPOSAL T1 \r\n" + 
				"			LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_FINAL_BUDGET  = 'Y'\r\n" + 
				"			LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG ='Y'\r\n" + 
				"			LEFT OUTER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE \r\n" + 
				"			INNER JOIN UNIT T6 ON  T1.HOME_UNIT_NUMBER= T6.UNIT_NUMBER\r\n" + 
				"			WHERE T1.STATUS_CODE = 11 AND T1.HOME_UNIT_NUMBER = :unitNumber";
//-------------------------------------------------------------Detailed LIST - AWARDED_PROPOSAL_WITHOUT_UNIT ----------------------------------------------------------------------------------------------			
		String DETAILED_AWARDED_PROPOSAL_WITHOUT_UNIT="SELECT T1.PROPOSAL_ID, T1.TITLE, T5.SPONSOR_NAME, T2.TOTAL_COST, T4.FULL_NAME AS PI, T6.UNIT_NAME, T1.SPONSOR_DEADLINE_DATE \r\n" + 
				"			FROM EPS_PROPOSAL T1 LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_FINAL_BUDGET = 'Y' 			\r\n" + 
				"			LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG ='Y' \r\n" + 
				"			INNER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE \r\n" + 
				"			INNER JOIN UNIT T6 ON  T1.HOME_UNIT_NUMBER= T6.UNIT_NUMBER \r\n" + 
				"			WHERE T1.STATUS_CODE = 11 AND T1.PROPOSAL_ID IN (\r\n" + 
				"									   SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = :personId \r\n" + 
				"									   UNION \r\n" + 
				"									   SELECT PROPOSAL_ID FROM EPS_PROPOSAL\r\n" + 
				"			                           WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = :personId) \r\n" + 
				"									   UNION \r\n" + 
				"									   SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = :personId\r\n" + 
				"									   UNION\r\n" + 
				"									   SELECT PROPOSAL_ID FROM EPS_PROPOSAL\r\n" + 
				"			                           WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = :personId AND UNIT_ADMINISTRATOR_TYPE_CODE = 3)\r\n" + 
				"															)";
//--------------------------------------------------------------------------Research summary Downloads------------------------------------------------------------------------------------------------------------------------------		

		String SELECT_FOR_RESEARCH_SUMMARY_DOWNLOADS = "SELECT PROPOSAL_ID,TITLE, SPONSOR_NAME, TOTAL_COST, PI,SPONSOR_DEADLINE_DATE FROM (";

		String SELECT_END = ") TAB";

		String DOWNLOAD_APPROVAL_INPROGRESS_PROPOSAL_LIST_WITH_UNIT = SELECT_FOR_RESEARCH_SUMMARY_DOWNLOADS + APPROVAL_INPROGRESS_PROPOSAL_LIST_WITH_UNIT + SELECT_END;

		String DOWNLOAD_APPROVAL_INPROGRESS_PROPOSAL_LIST = SELECT_FOR_RESEARCH_SUMMARY_DOWNLOADS + APPROVAL_INPROGRESS_PROPOSAL_LIST + SELECT_END;

		String DOWNLOAD_INPROGRESS_PROPOSAL_LIST_WITH_UNIT = SELECT_FOR_RESEARCH_SUMMARY_DOWNLOADS + INPROGRESS_PROPOSAL_LIST_WITH_UNIT + SELECT_END;

		String DOWNLOAD_INPROGRESS_PROPOSAL_LIST = SELECT_FOR_RESEARCH_SUMMARY_DOWNLOADS + INPROGRESS_PROPOSAL_LIST + SELECT_END;

		String DOWNLOAD_DETAILED_AWARDED_PROPOSAL_WITH_UNIT = SELECT_FOR_RESEARCH_SUMMARY_DOWNLOADS + DETAILED_AWARDED_PROPOSAL_WITH_UNIT + SELECT_END;

		String DOWNLOAD_DETAILED_AWARDED_PROPOSAL_WITHOUT_UNIT = SELECT_FOR_RESEARCH_SUMMARY_DOWNLOADS + DETAILED_AWARDED_PROPOSAL_WITHOUT_UNIT + SELECT_END;

//----------------------------------------------------------------------------Download for Donut Chart ---------------------------------------------------------------------------
		
		String SELECT_FOR_AWARD_DONUT = "SELECT PROPOSAL_NUMBER, TITLE, PI, PROPOSAL_TYPE,ACTIVITY_TYPE FROM (";
		
		String DOWNLOAD_AWARD_DONUT_WITH_SPONSOR_AND_UNIT = SELECT_FOR_AWARD_DONUT + AWARD_DONUT_WITH_SPONSOR_AND_UNIT + SELECT_END;

		String DOWNLOAD_AWARD_DONUT_WITH_SPONSOR = SELECT_FOR_AWARD_DONUT + AWARD_DONUT_WITH_SPONSOR + SELECT_END;

		String SELECT_FOR_PROPOSAL_DONUT = "SELECT PROPOSAL_ID, TITLE, PROPOSAL_TYPE, BUDGET, PI, SUBMISSION_DATE FROM (";
	
		String DOWNLOAD_PROPOSAL_DONUT_WITH_SPONSOR_AND_UNIT = SELECT_FOR_PROPOSAL_DONUT + PROPOSAL_DONUT_WITH_SPONSOR_AND_UNIT + SELECT_END;

		String DOWNLOAD_PROPOSAL_DONUT_WITH_SPONSOR = SELECT_FOR_PROPOSAL_DONUT + PROPOSAL_DONUT_WITH_SPONSOR + SELECT_END;

//---------------------------------------------------------------------------Download for Pie Chart---------------------------------------------------------------------------------
		
		String SELECT_FOR_AWARD_PIE_CHART = "SELECT AWARD_NUMBER, ACCOUNT_NUMBER, TITLE, SPONSOR_NAME, PI FROM (";

		String DOWNLOAD_AWARD_BY_SPONSOR_WITH_UNIT = SELECT_FOR_AWARD_PIE_CHART + AWARD_BY_SPONSOR_WITH_UNIT + SELECT_END;

		String DOWNLOAD_AWARD_BY_SPONSOR = SELECT_FOR_AWARD_PIE_CHART + AWARD_BY_SPONSOR + SELECT_END;

//---------------------------------------------------------------------------Units wit rigths of person--------------------------------------------------
		
		String GET_ALL_UNITS = "SELECT DISTINCT UNIT_NUMBER, UNIT_NAME, PARENT_UNIT_NUMBER from UNIT";

		String GET_QUESTIONNAIRE_ATTACHMENTS = "SELECT QUESTIONNAIRE_ANSWER_ATT_ID AS A, FILE_NAME AS B, CONTENT_TYPE AS C, UPDATE_USER AS D, UPDATE_TIMESTAMP AS E FROM QUEST_ANSWER_ATTACHMENT WHERE QUESTIONNAIRE_ANSWER_ID IN"
				+ " (SELECT QUESTIONNAIRE_ANSWER_ID FROM QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID IN "
				+ "(SELECT QUESTIONNAIRE_ANS_HEADER_ID FROM "
				+ "QUEST_ANSWER_HEADER T1 LEFT JOIN QUEST_HEADER T2 ON T1.QUESTIONNAIRE_ID = T2.QUESTIONNAIRE_ID"
				+ " WHERE T1.MODULE_ITEM_CODE = :MODULE_ITEM_CODE AND T1.MODULE_SUB_ITEM_CODE = :MODULE_SUB_ITEM_CODE AND "
				+ "T1.MODULE_ITEM_KEY = :MODULE_ITEM_KEY AND T2.IS_FINAL = 'Y'))";
//--------------------------------------------------------AGREEMENT-------------------------------------------------
		String AGREEMENT_SUMMARY_FOR_ADMIN = "SELECT T2.CATEGORY_CODE AS CATEGORY_CODE, T2.DESCRIPTION AS CATEGORYS,\n" + 
				"SUM(CASE WHEN T1.AGREEMENT_STATUS_CODE in (1,6) THEN 1 ELSE 0 END )AS \"DRAFT\",\n" + 
				"SUM(CASE WHEN T1.AGREEMENT_STATUS_CODE in (2,5,7) THEN 1 ELSE 0 END )AS \"IN WORKFLOW\"\n" + 
				"FROM AGREEMENT_HEADER  T1 \n" + 
				"INNER JOIN AGREEMENT_CATEGORY T2 ON T1.CATEGORY_CODE = T2.CATEGORY_CODE  \n" +
				"WHERE T1.AGREEMENT_REQUEST_ID IN ( \n" +
				"SELECT DISTINCT T4. AGREEMENT_REQUEST_ID FROM AGREEMENT_HEADER  T4 \n" +
				"LEFT JOIN AGREEMENT_PEOPLE T3 on T4.AGREEMENT_REQUEST_ID = T3.AGREEMENT_REQUEST_ID  \n" +
				"WHERE T1.AGREEMENT_SEQUENCE_STATUS NOT IN ('TEMPLATE') AND ((T1.UNIT_NUMBER IN(SELECT DISTINCT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('AGREEMENT_ADMINISTRATOR') AND PERSON_ID = :PERSON_ID) OR T3.PERSON_ID = :PERSON_ID OR T1.REQUESTOR_PERSON_ID = :PERSON_ID))) \n" + 
				"GROUP BY T2.CATEGORY_CODE,T2.DESCRIPTION";

		String AGREEMENT_SUMMARY_FOR_NON_ADMIN = "SELECT T2.CATEGORY_CODE AS CATEGORY_CODE,T2.DESCRIPTION AS CATEGORYS, SUM(CASE WHEN T1.AGREEMENT_STATUS_CODE in (1,6) THEN 1 ELSE 0 END )AS \"DRAFT\", \n" +
				"SUM(CASE WHEN T1.AGREEMENT_STATUS_CODE in (2,5,7) THEN 1 ELSE 0 END )AS \"IN WORKFLOW\" FROM AGREEMENT_HEADER  T1 \n" +
				"INNER JOIN AGREEMENT_CATEGORY T2 ON T1.CATEGORY_CODE = T2.CATEGORY_CODE  \n" +
				"WHERE T1.AGREEMENT_REQUEST_ID IN ( \n" +
				"SELECT DISTINCT T4. AGREEMENT_REQUEST_ID FROM AGREEMENT_HEADER  T4 \n" +
				"LEFT JOIN AGREEMENT_PEOPLE T3 on T4.AGREEMENT_REQUEST_ID = T3.AGREEMENT_REQUEST_ID  \n" +
				"WHERE T1.AGREEMENT_SEQUENCE_STATUS NOT IN ('TEMPLATE') AND ((T1.UNIT_NUMBER IN(SELECT DISTINCT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_ALL_AGREEMENT','MODIFY_ALL_AGREEMENT') AND PERSON_ID = :PERSON_ID) OR (T3.PERSON_ID = :PERSON_ID AND T3.PEOPLE_TYPE_ID = 3) OR T1.REQUESTOR_PERSON_ID = :PERSON_ID))) \n" + 
				"GROUP BY T2.CATEGORY_CODE,T2.DESCRIPTION";
}
